DeviceAdapters/MicroFPGA/Makefile.am
DeviceAdapters/MicroFPGA/MicroFPGA.cpp
DeviceAdapters/MicroFPGA/MicroFPGA.h
DeviceAdapters/MicroFPGA/MicroFPGA.vcxproj
DeviceAdapters/MicroFPGA/license.txt

Hi there,
Here is the device adapter for a FPGA board that the Ries lab (EMBL) and collaborators have been using for a few years on their microscopes. The platform is called [MicroFPGA](https://github.com/jdeschamps/MicroFPGA) and is based on an hobby FPGA board from Alchitry (Au or Cu, now produced by [SparkFun](https://www.sparkfun.com/categories/tags/alchitry)).
MicroFPGA generats various control signals used on microscopes such as a flexible laser triggering system, servomotors, TTL or PWM (used for instance together with a low-pass for analog output). Together with one of the FPGA board (Au), it can also read in analog signals.
We put some effort in making the [project repository](https://github.com/jdeschamps/MicroFPGA) as documented as possible so that it is easy for people to …

Add MicroFPGA

---

MMCore/LogManager.cpp
MMCore/LogManager.h

This PR fixes an error that prevent successful linking of MMCore on a GCC compiler. This is done by moving the definition of `LogManager::PrimarySinkMode` out of the header and into `LogManager.cpp`.
Up until C++17 where you can use `inline static` variable,  `static` member variables should not be defined inside a header. This is because even with `#pragma once` the definition will appear in any source file that includes the header, in this case `CMMCore.cpp` and `LogManager.cpp`, this then causes a problem when the object files are linked together.
I'm not sure why this issue doesn't appear on other compilers but it prevents successful compilation on GCC.

Fix linker error on GCC

---

DeviceAdapters/AndorSDK3/AndorSDK3.cpp
DeviceAdapters/MCL_MicroDrive/MCL_MicroDrive.vcxproj
DeviceAdapters/MCL_NanoDrive/MCL_NanoDrive.vcxproj
DeviceAdapters/PVCAM/PVCAMIncludes.h
DeviceAdapters/PrincetonInstruments/PVCAMInt.h
DeviceAdapters/PrincetonInstruments/PVCAMUniversal.cpp
DeviceAdapters/Sensicam/Sensicam.vcxproj.filters
DeviceAdapters/Spinnaker/SpinnakerCamera.h
DeviceAdapters/Spinnaker/SpinnakerCamera.vcxproj

@nicost , I don't currently have the ability to test the build but this should fix the issue with the Spinnaker camera. The SDK include paths were accidentally reverted when migrating to this submodule.
Don't merge this yet as I am still checking all the other device adapters for similar mistakes. Since we changed all "3rdParty" include paths from `..\..\..\3rdParty` to `$(MM_3RDPARTYPRIVATE)`, Git recognizes them all as having changed which means they must be checked manually to see if the path is actually different.
So far I have noticed a few other potential issues which I'm not sure how to properly resolve:
1: The ABS device adapter code from before merging the submodule uses `#ifdef LINUX`, while the current code uses `#ifdef __linux__` I'm not sure which is correct.
2: The AndorSDK3 …

Fix SDK include paths 

---

DeviceAdapters/Basler/BaslerPylon.vcxproj

make sure that the pylon 6.2 is existing in 3rdParty\Basler\windows\6.2.0
I have uploaded the pylon 6.2 once more
https://we.tl/t-FZFRllbQ9g

Basler Device adapter has been updated to pylon version 6.2

---

DeviceAdapters/TriggerScopeMM/TriggerScopeMMDAC.cpp

SetSignal function now stores the volt_ property that can be read
out by the OnVolt Property.

TriggerscopeMM: Fix bug seen when using DAZStage with DAC output.

---

DeviceAdapters/ASITiger/ASICRISP.cpp
DeviceAdapters/ASITiger/ASITiger.h

Added more states and an "Unknown" state so that we get less read errors when querying the CRISP State property. The 3.38 Tiger firmware should fix any remaining problems.

ASITiger: fix read errors for CRISP states

---

DeviceAdapters/ASIStage/ASIStage.cpp

Add an "Unknown" state to CRISP to match the new additions to ASITiger, GetFocusState uses the same switch statement as ASITiger as well.

ASIStage: add more CRISP states

---

DeviceAdapters/ASITiger/ASICRISP.cpp

The property limit for "Number of Averages" on ASITiger and ASIStage is now the same.

ASITiger: increase Number of Averages for CRISP

---

DeviceAdapters/VarispecLCTF/VarispecLCTF.cpp

This is just a few minor changes to make the VarispecLCTF device adapter a little better and catching errors when they occur rather than letting bytes pile up in the serial buffer resulting in confusing errors later.

Minor Varispec improvements

---

DeviceAdapters/ASITiger/ASIFWheel.cpp
DeviceAdapters/ASITiger/ASIFWheel.h
DeviceAdapters/ASITiger/ASITiger.h

This allows the user to set the filter wheel offset, which is followed by a home command so that the user can check the new offset.

ASITiger: add the offset property to the filter wheel device

---

DeviceAdapters/TriggerScopeMM/TriggerScopeMM.cpp
DeviceAdapters/TriggerScopeMM/TriggerScopeMM.h

The code figures out if the firmware supports this feature, and if so, exposes a Hub property.  Switching this off does not make much of a difference for the V3, but could result in significant speed improvements on the V4.

Adds option to control use of signal LEDs

---

DeviceAdapters/Motic/MoticCamera.cpp

Motic uses a zero-based binning, whereas we are 1-based.  Previous attempt left out some conversions.  Hopefully this will fix it.

MoticCAmera: second attempt to fix binning

---

DeviceAdapters/DirectElectron/src/DEClientLib/DENetwork.cpp
DeviceAdapters/SerialManager/AsioClient.h
buildscripts/VisualStudio/MMCommon.props

It would have been nice to keep the same Boost version, but that is impractical due to the old version (1.55.0) not fully working with VS2019. So update to the latest (1.77.0) and fix incompatibilities.
The number of projects failing to build (x64-Release) went from 32 to 22 with these changes.
The fixes to SerialManager and DEClientLib should not affect Unix builds that still use Boost 1.55.0. But they have not been tested for correct functioning.
Note: At the time of this writing, Boost 1.77.0 is still being uploaded (committed) to 3rdpartypublic (svn is taking its time).

Update Boost to 1.77.0 for VS2019

---

DeviceAdapters/Basler/BaslerPylon.vcxproj

The Basler Device Adapter will be built against pylon 6.3

Basler Device adapter has been updated to pylon version 6.3

---

DeviceAdapters/RaptorEPIX/HoribaEPIX.vcxproj
DeviceAdapters/RaptorEPIX/RaptorEPIX.cpp
DeviceAdapters/RaptorEPIX/RaptorEPIX.vcxproj
DeviceAdapters/RaptorEPIX/build.xml

EPIX headers and libraries used to be in SecretDeviceAdapters, where
they have now been removed. Repoint to 3rdparty.

RaptorEPIX: Move location of dependencies

---

DeviceAdapters/Basler/BaslerPylon.vcxproj
DeviceAdapters/RaptorEPIX/HoribaEPIX.vcxproj
DeviceAdapters/RaptorEPIX/RaptorEPIX.cpp
DeviceAdapters/RaptorEPIX/RaptorEPIX.vcxproj
DeviceAdapters/RaptorEPIX/build.xml

This PR brings `vs2019` up to date with `main`.
Automatic merge had no conflicts and was correct.
The RaptorEPIX and HoribaEPIX build was broken on `main` and now fixed.
To preserve the merge, please do not squash this PR.

Merge main into vs2019

---

DeviceAdapters/PointGrey/PointGrey.cpp

The PointGrey adapter is fixed by replacing the no longer existent `_ULongLong` identifier with `unsigned long long`.
Remaining question: Why cast to `unsigned long long` in the first place? Why not just pass the `unsigned int` variable directly.

PointGrey for vs2019

---

DeviceAdapters/FLICamera/FLICamera.vcxproj

After updating to vc142 the FLICamera device adapter fails to build with this message: `LNK2019: unresolved external symbol __snprintf referenced in function`
One possible solution may be to look at updating to a new version of the FLI SDK.
This PR does not do that but instead keeps using the SDK currently in the 3Party repository. Instead the build is fixed just by adding `legacy_ stdio_definitions.lib` to the linker.

Fix FLI Camera for vs2019

---

DeviceAdapters/Piper/CameraAdapter.cpp
DeviceAdapters/Piper/CameraAdapter.h

The Piper device adapter was using the `_Myptr()` method of `std::string` to write to the string buffer using `sprintf`. This no longer works so we now write to a `char[]` buffer.

Fix Piper camera device adapter for vs2019

---

DeviceAdapters/MP285/MP285.vcxproj
DeviceAdapters/XCiteLed/XCiteLed.vcxproj
DeviceAdapters/XCiteXT600/XCiteXT600.vcxproj

Two of the XCite project files had a "Version" option in the linker configuration which results in a syntax error in VS2019.
The version hasn't been updated in more than a decade and I doubt anyone knows it is there any way. This PR removes the version and enables building these device adapters on VS2019.

vs2019: Remove linker 'VERSION' flag from all projects

---

DeviceAdapters/WieneckeSinske/Makefile.am

Missing source files in Makefile.am resulted in missing symbols.

WieneckeSinske: Fix Unix build

---

DeviceAdapters/ThorlabsDCxxxx/Makefile.am

The Windows-only part of the code needs to be excluded from the build;
otherwise the device adapter contains missing symbols and does not load.

ThorlabsDCxxxx: Fix Unix build

---

DeviceAdapters/Standa8SMC4/Standa8SMC4.vcxproj

Update to XIMC 2.10.5 for Standa8SMC4 device adapter. Depends on 3rdParty rev 662

Fix VS2019 build for Standa8SMC4

---

buildscripts/VisualStudio/MMCommon.props

2.6.1 is the last 2.x version of protobuf. It may be perfectly fine to switch to 3.x; this is to be investigated in the future.
This allows the DirectElectron device adapter to build.

Use protobuf 2.6.1 built with VS2019

---

DeviceAdapters/Mightex/Mightex.vcxproj
DeviceAdapters/Mightex_BLS/Mightex_BLS.vcxproj

When building in debug mode these two device adapters would fail, apparently due to conflicting declarations found in the Windows 10 SDK and in the version of WinDDK included in the 3rdParty repository.
This PR fixes the VS2019 build by removing the WinDDK from the include path of the projects.
I'm not 100% sure but I think this means that WinDDK (1.3GB) could be removed from the 3rdParty repository.

Fix build of Mightex and Mightex_BLS for VS2019

---

DeviceAdapters/AndorSDK3/AndorSDK3.cpp
DeviceAdapters/AndorSDK3/SnapShotControl.cpp
DeviceAdapters/AndorSDK3/SnapShotControl.h

Fix to prevent micromanager hanging when the USB link resets and recovers.

Prevent hang when Zyla USB link recovers.

---

DeviceAdapters/TSI/TSI.vcxproj
DeviceAdapters/TSI/TSI3Cam.cpp
DeviceAdapters/TSI/TSILibrary.cpp
DeviceAdapters/TSI/tl_camera_sdk_load.c
DeviceAdapters/TSI/tl_camera_sdk_load.h

SDK has new functions and a reworked load file for DLLs. Changes are required for TSI camera users with SDK v2.0.1.

Update TSI device adapter load files to work with SDK 2.0.1 DLLs

---

DeviceAdapters/PicardStage/PicardStage.cpp

Due the lack of default value for homing in the CPiStage, it is randomly considered as indefinitely busy when loading a configuration.
Adding the default value (false) should prevent random device timeouts at launch.

Fix PicardStage timing out

---

DeviceAdapters/IDS_uEye/IDS_uEye.cpp
DeviceAdapters/IDS_uEye/IDS_uEye.h

Porting some additions we made to MM 1.4 IDS uEye device adapter to MM 2.0 code base.
https://github.com/biophotonics-bielefeld/ids-device-adapter
This PR is three commits, adding:
* User-settable camera ID, allows for running multiple IDS cameras in MM
* Option to control the 'flash output' (TTL-style exposure state output) of the cameras
* In-camera timestamp (and IO port state) gets added to metadata in sequence acquisitions
All of these *should* be backwards compatible with current configurations, as default values (camera id 1, flash off) match those used by the current adapter.

IDS_uEye additional features

---

DeviceAdapters/IDS_uEye/IDS_uEye.vcxproj

IDS Software Suite 4.30.00 -> 4.95.1.
This was needed to work with the changes in #142.

Use newer SDK for IDS uEye to build

---

DeviceAdapters/Diskovery/Diskovery.cpp
DeviceAdapters/Diskovery/DiskoveryModel.cpp

Taking the address of a temporary value does not work.
Previous code could have been working by coincidence, but does not compile in modern C++.

Fix Diskovery C++ errors

---

README.md

I always go here first to find these, then remember I have to go pymmcore in order to find a link. Nice to also have them here.
I added the second link because the main page is currently empty of content (ill open an issue about that) and CMMCore is probably the thing most people will be looking for.

Add links to api docs to readme

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h

Allows for more comprehensive testing of downstream libraries.
It seems that it was necessary to make a follower and leader property
as with only a single property there is a callback fired as soon
the action returns, so added a second "Follower" property that
is set to the leaders value after a (configurable) delay.

Add async property callback to DemoCamera

---

DeviceAdapters/HamiltonMVP/unittest/Makefile.am
DeviceAdapters/UserDefinedSerial/unittest/Makefile.am
DeviceAdapters/configure.ac
MMCore/unittest/Makefile.am
MMDevice/unittest/Makefile.am

Probably was neglected when mmCoreAndDevices was split out.
This does not fully fix `make check` at the toplevel of `micro-manager`, due to unmaintained Java tests, but does fix `make check` in all C++ subdirectories of `mmCoreAndDevices`.

Repair C++ unit tests (Unix build)

---

MMCore/MMCore.cpp
MMCore/MMCore.h
MMCore/unittest/APIError-Tests.cpp
MMCore/unittest/Makefile.am

Partially addresses #165.
Closes #105.
- Take reasonable actions on error in functions that are not marked `throw (CMMError)`
- Deprecate functions related to `PropertyBlock`, a seldom (never?) used feature, many of which will potentially crash
- Deprecate functions related to ImageSynchro (not related to crashes but mentioned in https://github.com/micro-manager/mmCoreAndDevices/issues/164#issuecomment-1054815138)

Prevent Core from crashing due to uncaught exceptions

---

DeviceAdapters/QCam/QICamera.cpp
DeviceAdapters/QCam/QICamera.h
DeviceAdapters/SerialManager/SerialManager.cpp
DeviceAdapters/SutterLambda/SutterLambda.cpp
DeviceAdapters/TwainCamera/TwainDevice.cpp
DeviceAdapters/UserDefinedSerial/ResponseDetector.cpp
DeviceAdapters/UserDefinedSerial/ResponseDetector.h
DeviceAdapters/UserDefinedSerial/UserDefinedSerial.h
DeviceAdapters/UserDefinedSerial/UserDefinedSerialImpl.h
MMCore/Error.cpp
MMCore/Error.h

Replace with std::unique_ptr, and add std::move() where necessary (one
location). Remove redundant initialization to 0 (nullptr) where it
causes ambiguity.

Eliminate deprecated std::auto_ptr

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h

Avoids errors when changing exposure time midway a sequence. Addresses hang reported in https://github.com/micro-manager/micro-manager/issues/1409.

DemoCamera: easier and more reliable way to calculate emulated exposure time. 

---

.github/workflows/sync-micro-manager-submodule.yml

The line removed here led to an error in the case that the submodule is
already up to date, and the main repo had the submodule remote tracking
branch set to the default (i.e. branch not set in .gitmodules).
There should be no need to force-set the submodule branch; we should
just ensure that it is set correctly in any branch of the main repo.
None of this matters unless we use a long-lived branch with
semi-official status anyway (as we did with the 'vs2019' branches of
each repo).

Avoid forced set-branch when syncing to submodule

---

DeviceAdapters/SutterLambda/SutterLambda.cpp
DeviceAdapters/SutterLambda/SutterLambda.h
DeviceAdapters/SutterLambda/SutterLambda.vcxproj

Fix Unix build following #193.
@dscbiggs Could you take a look at my first commit ('Remove redundant/dead code') and make sure it is correct? I'm not sure what the role of the second parameter (`id`) to the `ShutterOn721` constructor is. There were lines setting `id` to `0` and `3`; I removed the one using `3` because it never would have been reached.
(Also, just to check, is it correct to pass `3` as the `id` to the `Wheel` constructor in the case of `g_WheelLambda721Name`?)

Sutter lambda fix unix build

---

DeviceAdapters/TISCam/TIScamera.cpp
DeviceAdapters/TISCam/TIScamera.h

More sensible handling of DeNoise and Autogain properties.  
However, there is some strange stuff going with camera selection.  Apparently, initialization partly
happens in the SetupProperties fundtion so that selection of other cameras is possible after the 
initialize function.  This currently does not work and causes MM to hang.   As long as nobody tries to 
use multiple TIS cameras at the same time (and not use those properties that cause MM to hange)
all should be good.

The Imaging Source cameras

---

DeviceAdapters/Spinnaker/SpinnakerCamera.cpp

This PR fixes bugs during ROI setting of Spinnaker cameras. For example, previously an error would arise if attempting to set the ROI to (0, 0, 100, 100) due to the way increments in OffsetX and OffsetY are handled. This PR addressed this bug and as a result would set ROI position that is slightly different (<OffsetX.GetInc() pixels) compared to the previous version.

fix bugs in SpinnakerCamera ROI settings

---

DeviceAdapters/Utilities/Makefile.am

Without this fix the adapter builds without errors but fails to load at runtime due to undefined symbols:
```Failed to load device "Multi Camera" from adapter module "Utilities" [ Failed to load device adapter "Utilities" [ Failed to load module "/home/tom/uM/build-mm2-ImageJ/ImageJ/libmmgr_dal_Utilities.so.0" [ /home/tom/uM/build-mm2-ImageJ/ImageJ/libmmgr_dal_Utilities.so.0: undefined symbol: _ZN18MultiDAStateDeviceC1Ev```
All undefined symbols were related to local sources not taken to build, filtered out with:
```objdump -a -x libmmgr_dal_Utilities.so.0 | grep -e "0000[^a-zA-Z]*\*UND\*"```

Utilities: Fixed Makefile to build all sources

---

DeviceAdapters/Dragonfly/FilterWheelProperty.cpp
DeviceAdapters/Dragonfly/PositionComponentHelper.cpp

If a filter wheel position string length is bigger or equal to the
buffer it is going to be stored in, it is missing a terminal 0.
This leads to scrambled text stored in the property value preventing
the use of this value.

Dragonfly: Fix filter wheel position description

---

camera_triggering_API.md

@jondaniels @bls337 Are these methods sufficient for light sheet mode? My understanding is that if you know the exposure, along with these two params, everything you need can be calculated.
I used "Line offset" because I think the "line time" that some camera manufacturers use is a bit confusing--I would think "line time" means the full line, rather than the delay between lines. But we could use different terminology if you think it's better.
Also, I use "rolling shutter" instead of "light sheet", because I think that is a more general way to describe these features, and it would be easier for a light sheet person to understand they need to manipulate "rolling shutter" than a non-light sheet person to understand they need to manipulate "light sheet" mode. And I have  bit of a bias towards …

add light sheet rolling shutter options

---

DeviceAdapters/ASIStage/ASICRISP.cpp

Adds a read-only property that reads the member variable "axis_", which is set using  a pre-init property named "Axis". This means that you can use "AxisLetter" in both the ASIStage/ASITiger device adapters now.

ASIStage: Add read-only property "AxisLetter" to CRISP

---

DeviceAdapters/Utilities/DAShutter.cpp

have a DA Shutter in them.  This can not have worked previously.

Utilities: DA Shutter, do not fail to load config files that

---

DeviceAdapters/ZeissCAN29/ZeissCAN29.cpp
DeviceAdapters/ZeissCAN29/ZeissCAN29.h

I was having an issue on an x64 Linux computer
with incorrect absolute XY stage positions being read. After some investigation I tracked it down to it accessing uninitialized memory due to an invalid cast.
ZeissLong is only 4 bytes, but on (most?) 64-bit machines a long is
8 bytes. There were parts of the code that were casting a long
to a ZeissLong leading to undefined values for values that were
being read.
I tried to clean it up in a few positions, although the specific bug that I was facing stemmed from XYStage::GetPositionSteps: 
https://github.com/micro-manager/mmCoreAndDevices/compare/micro-manager:300caa5...wxs:c5a8242#diff-f2bd135a3e8514850d9899bb795dc4dbd273a9bb1ef492871da41077b33cd027R1891
I also changed some typedefs to make the integer sizes explicit, as this could be an …

Fix Zeiss uninitialized memory issue

---

DeviceAdapters/Dragonfly/Disk.cpp

Allow disk speed to be monitored and displayed in the UI while the disk is stopping.

Dragonfly: Monitor disk speed on stop

---

DeviceAdapters/ASITiger/ASICRISP.cpp
DeviceAdapters/ASITiger/ASICRISP.h

When using Tiger firmware >= 3.40, CRISP will now use LK Y? and LK T? instead of EXTRA X? to query the "Dither Error" and "Sum" respectively.
This also gets rid of the weird dependency between "Dither Error" and "Sum" where you would need to call dither error first to the set the sum value, and then call the get sum method in older firmware. It may be slightly slower, but the values can be queried independently now.

ASITIger: use faster serial commands for CRISP

---

MMCore/Semaphore.cpp
MMCore/ThreadPool.cpp

The usage removed here was introduced in as a workaround for standard lambdas when we were still building with C++03. It is no longer necessary.

Retire Boost.Phoenix

---

MMCore/Devices/DeviceInstance.h
MMCore/LoadableModules/LoadedDeviceAdapter.h

Error exposed on Linux by previous change (#264).

MMCore: Add missing header for std::memset()

---

MMCore/MMCore.cpp
MMCore/TaskSet_CopyMemory.cpp

Exposed on Linux by previous change (#265).

MMCore: Add missing include for std::memcpy()

---

MMCore/Devices/DeviceInstance.h
MMCore/LoadableModules/LoadedDeviceAdapter.h
MMCore/LoadableModules/LoadedModule.h
MMCore/LoadableModules/LoadedModuleImpl.h
MMCore/Logging/GenericLogger.h
MMCore/Logging/GenericStreamSink.h

Replace it with the C++11+ way (copy constructor and copy assignment operator deleted).

MMCore: Retire boost::noncopyable

---

DeviceAdapters/ASIStage/ASICRISP.cpp
DeviceAdapters/ASIStage/ASICRISP.h

The "LED Intensity" device property now sends serial commands to the controller, it previously had no effect and only modified a internal device adapter variable.
The max "number of averages" is now 8 to be in line with the internal firmware limits.
The dependency on calling "Dither Error" first to update the cached "Sum" value is no longer a thing, each action handler sends EXTRA X? and parses the result to get the right value every time. (removal of sum_ cached value)

ASIStage: Fix CRISP "LED Intensity" property

---

DeviceAdapters/ASIStage/ASIBase.cpp
DeviceAdapters/ASIStage/ASIBase.h
DeviceAdapters/ASIStage/ASICRISP.cpp
DeviceAdapters/ASIStage/ASICRISP.h
DeviceAdapters/ASIStage/ASIStage.h

Use LK T? and LK Y? instead of EXTRA X? when new firmware is detected (>= 9.2o).

ASIStage: use fast serial commands for CRISP

---

MMDevice/MMDevice.h

- Make the default constructor simpler and remove empty destructor
- Add static member functions to construct from seconds, milliseconds, or microseconds
- Remove constructor from std::string (nowhere used)
- Comment `serialize()` as being deprecated (rarely used; used only for debug logging)
- Remove TimeoutMs private copy constructor and copy assignment operator (I do not see any reason to prevent copy)

MMDevice: Clean up MMTime and TimeoutMs

---

MMCore/CircularBuffer.cpp
MMCore/CircularBuffer.h
MMCore/CoreCallback.cpp
MMCore/CoreCallback.h
MMCore/CoreUtils.h
MMCore/Logging/GenericPacketQueue.h
MMCore/Logging/Metadata.h
MMCore/Logging/MetadataFormatter.h
MMCore/MMCore.cpp
MMCore/PluginManager.cpp
MMCore/TaskSet.h

Convert all but `MM::Time` (`GetCurrentMMTime()`) implementation, which requires resolving #273.
Setting as draft until I finish testing.

MMCore: Replace most uses of Boost.Date_Time with std::chrono

---

DeviceAdapters/PICAM/PICAMUniversal.cpp
DeviceAdapters/PVCAM/PVCAMUniversal.cpp
DeviceAdapters/Ximea/XIMEACamera.cpp
MMDevice/DeviceBase.h
MMDevice/MMDevice.h

So that we can change the internal representation without affecting user code.
Fortunately only 1 device adapter (XIMEA) needed small changes.

Make MMTime data members private

---

MMDevice/MMDevice.h
MMDevice/unittest/MMTime-Tests.cpp
MMDevice/unittest/Makefile.am

- It looks like the previous behavior forced negative values to zero, except that if `sec_ >= 0` and `uSec_ < 0` it will store `sec_ = -1`; also, if constructed from a negative `double`, it will store negative `sec_` (clearly a bug).
- Therefore, any code that results in negative MMTime values is probably already broken (such code is probably rare).
- Most usage would benefit from making negative values work as expected. However, if the result is used as an argument to sleep, there could be trouble (because the argument will be interpreted as unsigned) if we change the behavior away from clamping to zero. Fortunately, on review of all uses of `CDeviceUtil::SleepMs()`, `Sleep()`, `sleep()`, `usleep()`, and `nanosleep()`, it does not appear that any derive their argument from an `MMTime` …

Make MMTime handle negative values correctly

---

MMCore/CircularBuffer.cpp
MMCore/Logging/GenericPacketQueue.h
MMCore/Logging/MetadataFormatter.h
MMCore/MMCore.cpp

- Unused variables
- Local variable definition hides previous definition

MMCore: Fix compile warnings

---

MMCore/CoreCallback.cpp
MMCore/CoreCallback.h
MMCore/CoreUtils.h
MMCore/MMCore.cpp
MMDevice/MMDevice.h

Closes #273.
This replaces the Boost-based implementation that purported to use the time since 2000-01-01, but actually added a time-zone-dependent offset. The new implementation has no fixed epoch (time zero) but uses a monotonic clock and is suitable for time delta measurement (which is what MM::MMTime is used for).
Setting to draft until I finish testing.

MMCore: use std::chrono::steady_clock for GetCurrentMMTime()

---

DeviceAdapters/DirectElectron/vsprojects/DEClientLib.vcxproj
DeviceAdapters/DirectElectron/vsprojects/DEMessaging.vcxproj
MMCore/Makefile.am
MMCore/unittest/Makefile.am
MMCoreJ_wrap/Makefile.am
MMDevice/unittest/Makefile.am
buildscripts/VisualStudio/MMCommon.props
buildscripts/VisualStudio/MMDeviceAdapter.props

On Unix, remove flags from Makefile.am (configure.ac in the micro-manager repo needs separate update).
On Windows, no longer provide Boost incdir/libdir in MMCommon.props, but instead make it the default in MMDeviceAdapter.props and add to non-device-adapter projects that require Boost.

Remove Boost dependency from MMCore build

---

MMCore/MMCore.h

These never really belonged in MMCore (they are only there because it was a convenient place to get C++ functions wrapped for Java) and these days there are better alternatives in Java and Python. Removing these has a small benefit of simplifying the build config on macOS (and potentially Windows), aside from removing code that need maintenance (the macOS implementation currently gets a deprecation warning).

MMCore: Deprecate user id/host name/MAC functions

---

MMDevice/MMDevice.h

Belatedly, for the MMTime struct layout change in #281 (specifically, commit 179b5fc86e133b243d4663b744f1f27789ad052c).
Closes #288.
If we merge this today (as I plan to), it will mean that the following nightly builds had incorrect device interface version (70) despite having actual binary interface 71:
20221030, 20221028, 20221027
In addition, 20221026 and 20221025 (since #277 commit 8ba45cde4436f8331f26a1adfac858ba08d51731) may have yet another incompatible interface (true at least [on macOS](https://github.com/micro-manager/mmCoreAndDevices/issues/288#issuecomment-1297655209)).

Increment device interface version (70 -> 71) for MMTime change

---

MMCoreJ_wrap/MMCoreJ.i

Building with SWIG 4+ results in errors, possibly later in the build (in MMStudio, because SWIG 4 changed some of the wrapped types). Until now, this was confusing and has resulted in multiple issues filed. (See #37.)
Until we have a proper fix for SWIG 4, let's make it fail immediately with the correct error message.

Require SWIG 2.x or 3.x to build MMCoreJ

---

DeviceAdapters/MicroFPGA/MicroFPGA.vcxproj
DeviceAdapters/MicroFPGA/MicroFPGA.vcxproj.filters

Related to 
https://github.com/micro-manager/mmCoreAndDevices/issues/207
https://github.com/micro-manager/mmCoreAndDevices/issues/292
- Removed Win32 builds
- Set PlatformToolset to v142
- Add filters

Fix Mufpga project files

---

MMCore/MMCore.cpp
MMCoreJ_wrap/MMCoreJ.i

That was remarkably simple.  However, do not merge (yet).  Consequences are unexpected: In both Live and Snap mode, the "user" tags contain the system state cache, which disappear after running `mmc.setIncludeSystemCache(true)` in the script panel.  However, the system cache is also contained in the "device" tags, presumably entered somewhere upstream in the code.  That makes me believe we should remove the addition of the systemStateCache altogether. There is some work needed to do so, because running an MDA with 3 Z positions after `mmc.setIncludeSystemCache(true)` results in:
```
2022-11-24T07:59:59.783280 tid33644 [IFO,App] 
[       ] java.lang.IllegalArgumentException: Failed to convert TaggedImage tags to metadata in Thread[TaggedImage sink thread,6,main]
[       ]   at …
```

MMCoreJ.i: added code to make adding the system cache to tagged images conditional.

---

DeviceAdapters/89NorthLDI/LDI.cpp

Also removed a statement that always was true.  Not quite sure why there is a timeout in the loop reading the response (even though the serial port already has its own timeout), but leave that to avoid unexpected side effects.

89North LDI: handle unsolicited ok.

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h

This PR adds the ability to sequence the State property of the `DStateDevice`. This is helpful in testing the channel sequencing capabilities of the acquisition engine as in https://github.com/micro-manager/pycro-manager/pull/458.
Here I also remove the Delay capability of the `DStateDevice`, which overlaps in functionality with `DWheel`.
In a future PR, I plan to rename the device from `DemoCamera` to `DemoHub` and separate the device across individual `.cpp` files.

Add State Sequencing to DStateDevice

---

DeviceAdapters/NIDAQ/NIDigitalOutputPort.cpp

NIDAQ: Fix bug causing blanking property to disappear when reloading the device adapter when blanking is on. Fixed by checking for blanking in the Shutdown function and stop blanking if it was on.

NIDAQ: Fix bug causing blanking property to disappear

---

DeviceAdapters/SigmaKoki/Camera.cpp
DeviceAdapters/SigmaKoki/Camera.h
DeviceAdapters/SigmaKoki/Shutter.cpp
DeviceAdapters/SigmaKoki/Shutter.h
DeviceAdapters/SigmaKoki/SigmaBase.cpp
DeviceAdapters/SigmaKoki/SigmaBase.h
DeviceAdapters/SigmaKoki/SigmaKoki.vcxproj
DeviceAdapters/SigmaKoki/SigmaKoki.vcxproj.filters
DeviceAdapters/SigmaKoki/XYStage.cpp
DeviceAdapters/SigmaKoki/XYStage.h
DeviceAdapters/SigmaKoki/ZStage.cpp
DeviceAdapters/SigmaKoki/ZStage.h
DeviceAdapters/SigmaKoki/license.txt
micromanager.sln

SigmaKoki device adapter/open source

add SigmaKoki Adapter

---

DeviceAdapters/DemoCamera/DemoCamera.cpp

This PR adds 11-bit image mode for DCam which is useful in troubleshooting

11-bit mode for DCam

---

DeviceAdapters/Pixelink/Pixelink.cpp
DeviceAdapters/Pixelink/Pixelink.h
DeviceAdapters/Pixelink/Pixelink.vcxproj
DeviceAdapters/Pixelink/Pixelink.vcxproj.filters
DeviceAdapters/Pixelink/README.txt
DeviceAdapters/Pixelink/license.txt

Adding the Pixelink Micromanager Device Adapter to micromanager. This allows Micromanager users to operate Pixelink PL-D and PL-X cameras.

Adding the Pixelink Micromanager Device Adapter

---

DeviceAdapters/Pixelink/Pixelink.vcxproj
micromanager.sln

Follow-up to #315.
Project file has been normalized by removing 32-bit, post-build events, and unnecessary settings, and using 3rdparty for library and headers.

Pixelink: Update vcxproj and add to solution

---

MMCore/Semaphore.cpp
MMCore/Semaphore.h
MMCore/Task.h
MMCore/TaskSet.cpp
MMCore/TaskSet.h
MMCore/TaskSet_CopyMemory.cpp
MMCore/TaskSet_CopyMemory.h
MMCore/ThreadPool.cpp
MMCore/ThreadPool.h

The ```ThreadPool``` and related task classes were originally developed as a part of PVCAM device adapter and later copied to MMCore where the same functionality is needed. So far these classes are not considered a part of public API of MMCore, thus we have two copies.
This PR basically synchronizes the implementation with changes done in PVCAM adapter, namely using ```std::unique_ptr``` to store thread instances (that addressed a TODO note), restricting the task types to derive from ```Task``` base class, used C++11 keywords like ```override``` or ```final```.
The two copies of each file now differ only in one line in the copyright header comment stating the actual module name the code belongs to.

MMCore: Cosmetic changes to thread pool and task classes

---

DeviceAdapters/MicroFPGA/MicroFPGA.cpp

Hi!
A small update of MicroFPGA device adapter:
- Change error message to include most common problem (wrong baudrate)
- Change (seemingly...) the default baudrate 
Now a small question before merging: I tested the new version of the adapter and the [default value of the baudrate](https://github.com/jdeschamps/mmCoreAndDevices/blob/afcad44dddeb3cef1a1a2accd75a997f29941a3e/DeviceAdapters/MicroFPGA/MicroFPGA.cpp#L194) is not effective. I still get "9600" when using the hardware configuration wizard. Do you have any idea why?
I can also open an issue or post on the forum.

MicroFPGA: update

---

MMCore/MMCore.cpp

(Accidentally opened this on different branch before https://github.com/henrypinkard/mmCoreAndDevices/pull/2)
I don't have access to my setup Core dev environment at the moment, so it would be great if someone can verify if this change is correct (or if not I can do it in a few weeks).
With the current version of the acq engine, a bug has arisen where the expected number of images don't arrive if an ROI has been set. See: https://github.com/micro-manager/pycro-manager/issues/620. We also have a automated test in PM that checks this (which currently fails): https://github.com/micro-manager/pycro-manager/pull/638
The bug seems to arise from difference between the two versions of`startSequenceAcquisition` which take a camera label vs using `Core-Camera`. The acquisition engine uses the …

 Fix bug related to changing setting ROIs and starting sequence acquisitions

---

DeviceAdapters/PointGrey/PointGrey.cpp

This change addresses the problem with the Point Grey device adapter that is described in #363 . MM is currently compiled against FlyCap 2.13.3.61, but a version check in the device adapter code requires a DLL from version 2.10.3.266. This mismatch renders the current device adapter code unusable.
I verified that this change works on a Flir Grasshopper3 U3-23S6M.

Update FlyCap2 version check in Point Grey device adapter

---

DeviceAdapters/TriggerScopeMM/TriggerScopeMM.cpp
DeviceAdapters/TriggerScopeMM/TriggerScopeMMTTL.cpp

If another device (in this case the RAP UGA40) send data to the COM port before TriggerScopeMM initialization, the device would fail.  This PR fixes that problem, by requesting device identification once more when the device returns an error.
Also, fixes wrong TTL device name, and several compiler warnings.

TriggerScopeMM: Attempt to deal with garbage send to COM port earlier.

---

DeviceAdapters/Zaber/Makefile.am
DeviceAdapters/Zaber/Zaber.vcxproj

With corrected ZML on 3rdpartypublic, C++17 is no longer required.
See https://github.com/micro-manager/mmCoreAndDevices/pull/359#issuecomment-1696564608

Zaber: Revert C++17 requirement

---

DeviceAdapters/Makefile.am
DeviceAdapters/Zaber/Makefile.am
DeviceAdapters/configure.ac

Closes #368.
Without this, 3rdpartypublic is required for the Mac/Linux build. We want to keep it so that only 3rdpartypublic/classext is required on those platforms (and not even that with `--without-java`).
This change also removes the special rpath flags. In the official macOS build, dependency paths are handled by a spearate script. On Linux, the only currently supported way is to build on the system where MM will be run, so (I hope) it is not necessary to use a special flag.

Zaber: Skip build when ZML not found

---

DeviceAdapters/Zaber/Makefile.am
DeviceAdapters/configure.ac

For now this is probably the simplest way to make Zaber work when built under Linux. The copy only happens if Zaber is being built.
Also restore the setting of rpath to `$ORIGIN` in the Zaber device adapter.
@martinzak-zaber Can you check that this works for you?

Zaber: Copy ZML libs during Linux install

---

MMCore/ConfigGroup.h

This does not currently cause problems because the argument is pre-checked by `CMMCore::setPixelSizeAffine()`, but fixing to avoid future problems.

Throw object, not pointer, in C++

---

MMCore/Devices/AutoFocusInstance.cpp
MMCore/Devices/CameraInstance.cpp
MMCore/Devices/DeviceInstance.cpp
MMCore/Devices/DeviceInstance.h
MMCore/Devices/GalvoInstance.cpp
MMCore/Devices/HubInstance.cpp
MMCore/Devices/ImageProcessorInstance.cpp
MMCore/Devices/MagnifierInstance.cpp
MMCore/Devices/SLMInstance.cpp
MMCore/Devices/SerialInstance.cpp
MMCore/Devices/ShutterInstance.cpp
MMCore/Devices/SignalIOInstance.cpp
MMCore/Devices/StageInstance.cpp
MMCore/Devices/StateInstance.cpp
MMCore/Devices/XYStageInstance.cpp
MMCore/MMCore.cpp
MMCoreJ_wrap/pom.xml

- Most non-property operations require an initialized device
- Pre-init properties must not be set after initialization
- Device initialiation may only be attempted once per device instance
These rules have been unstated previously, but had to be observed. Now make it an error (throw a `CMMError`).
All `CMMCore` member functions that do _not_ throw `CMMError` were reviewed to make sure newly-thrown exceptions are not left uncaught in SWIG wrappers.
MMCore version bumped 10.4.0 -> 10.5.0.
Closes #366.
Cc: @tlambert03

MMCore: Enforce pre/post initialization rules

---

DeviceAdapters/IntegratedLaserEngine/ILEWrapper/ILEWrapper.cpp

Remove mandatory support for a feature specific to HLE only available in recent versions of the ALC library. This feature is now optional so as to allow support for ILE when using older versions of the ALC library.

ILE: remove dependency on newer ALC lib

---

MMCore/Devices/AutoFocusInstance.cpp
MMCore/Devices/CameraInstance.cpp
MMCore/Devices/DeviceInstance.cpp
MMCore/Devices/DeviceInstance.h
MMCore/Devices/GalvoInstance.cpp
MMCore/Devices/HubInstance.cpp
MMCore/Devices/ImageProcessorInstance.cpp
MMCore/Devices/MagnifierInstance.cpp
MMCore/Devices/SLMInstance.cpp
MMCore/Devices/SerialInstance.cpp
MMCore/Devices/ShutterInstance.cpp
MMCore/Devices/SignalIOInstance.cpp
MMCore/Devices/StageInstance.cpp
MMCore/Devices/StateInstance.cpp
MMCore/Devices/XYStageInstance.cpp
MMCore/MMCore.cpp
MMCoreJ_wrap/pom.xml

When an operation that requires an initialized device is attempted on an uninitalized device, log a warning message instead of throwing an exception. This reverts part of #376; see #384 for some background.
It turns out that the Hardware Configuration Wizard currently relies (mostly incorrectly) on some operations that are not actually correct, but fixing it is complicated enough that we need to revert the exception throwing for now.
In addition, MMCore itself needs some fixes so that functions like waitForSystem() do not cause issues in the presence of uninitialized devices. This may also apply to other bulk actions such as unloadAllDevices() and the system state cache.
The goal is still to enable exceptions for these checks, but only once we've had a chance to fix these issues.
This …

MMCore: Revert strict initialization checks

---

DeviceAdapters/AndorSDK3/AOIProperty.cpp

Fix for AOI's for Sona-6 which is now 2048 x 2046 pixels.

Update AOI options for Andor Sona

---

MMCore/Devices/DeviceInstance.h
MMCore/MMCore.cpp
MMCore/MMCore.h
MMCoreJ_wrap/pom.xml

Closes #378.
Using `enum` rather than C++11 `enum class` for SWIG 3.x compatibility.
MMCore(J) version 10.7.0.

MMCore: Add getDeviceInitializationState()

---

MMCore/CoreFeatures.cpp
MMCore/CoreFeatures.h
MMCore/Devices/DeviceInstance.cpp
MMCore/MMCore.cpp
MMCore/MMCore.h
MMCore/MMCore.vcxproj
MMCore/MMCore.vcxproj.filters
MMCore/Makefile.am
MMCoreJ_wrap/pom.xml

Also add the feature "StrictInitializationChecks".
Closes #394.
~~Sorry for the spurious removal of trailing whitespaces.~~

MMCore: Add enableFeature() and isFeatureEnabled()

---

DeviceAdapters/ZeissCAN/mcu28.cpp

ZeissCAN: Fix x-y typo in Y_um property

---

MMCore/Devices/DeviceInstance.cpp
MMCore/MMCore.cpp
MMCoreJ_wrap/pom.xml

Before this change: Setting a pre-init property after initialization is an error.
After this change: Setting a pre-init property after initialization is an error if Core feature StrictInitializationChecks is enabled. Otherwise it is a warning.
Bump MMCore version to 11.1.1.
(We probably need to special case SerialManager ports, to allow port scanning to work. But for now remove the error for all devices to give us time to decide what exactly needs to be allowed.)
Related to: https://github.com/micro-manager/mmCoreAndDevices/issues/384#issuecomment-1796571576

Relax check against setting a pre-init property after initialization

---

buildscripts/VisualStudio/MMCommon.props

(As opposed to, and in addition to, parallel building of projects.)
For human developers, this means:
- When building a single project in Visual Studio (e.g. by right-clicking), compilation is parallelized (this being the motivation for the change).
- When building the whole solution (presumably not very common), both files within each project and projects in the solution are parallelized, both up to the CPU count, which is not ideal but doesn't appear to affect the total build time appreciably.
- It may make the computer a little less responsive.
- The project-level parallelism can be adjusted under Tools > Options... > Projects and Solutions > Build And Run.
For the automated build, this means:
- There will be a similar excess parallelization, hopefully with no negative consequences. If …

Enable parallel build for each VS project

---

DeviceAdapters/BH_DCC_DCU/DCCDCUDevices.h
MMDevice/Property.h

This is like `CPropertyAction[Ex]`, but takes an arbitrary copyable callable (such as a lambda).
One of the frustrating things about device properties is that the code that deals with each property tends to be scattered in several different parts of the code of a device adapter. Defining a property action using a lambda allows one to put all the code related to a single property in one place.
For example usage, see the BH_DCC_DCU device adapter (DCCDCUDevices.h), which is updated here to use the version in MMDevice.
Since this addition is internal to MMDevice (not visible to MMCore), no change to the device interface version is required.

Add ActionLambda to MMDevice

---

.github/workflows/ci-mmdevice-mmcore.yml
MMCore/meson.build
MMCore/subprojects/.gitignore
MMCore/subprojects/gtest.wrap
MMCore/unittest/meson.build
MMDevice/meson.build
MMDevice/subprojects/.gitignore
MMDevice/subprojects/gtest.wrap
MMDevice/unittest/meson.build

The immediate benefit is that this allows us to run the unit tests for MMDevice and MMCore, which we've never had running in CI previously (and were never run on Windows at all). See the included GitHub workflow.
This build is not (so far) appropriate for building MMCore for distribution or actual use. That will come eventually.
This has no effect on the existing Visual Studio and Autoconf/Automake builds, which need to be kept maintained.
This is a first step toward micro-manager/micro-manager#1392. It's a little out of order compared to the [plan](https://github.com/micro-manager/micro-manager/issues/1392#issuecomment-1156956436) outlined there (which had MMCoreJ first); I intend to create a separate overview issue (in _this_ repo) for the C++ parts of the build modernization, with some …

Experimental Meson build for MMDevice and MMCore

---

MMCore/CircularBuffer.cpp
MMCore/CircularBuffer.h
MMCore/ConfigGroup.h
MMCore/Configuration.cpp
MMCore/Configuration.h
MMCore/MMCore.cpp
MMCore/MMCore.h
MMCore/MMCore.vcxproj
MMCore/meson.build
MMDevice/ImageMetadata.h
MMDevice/Property.cpp

So far removes warnings on macOS/Clang. Keeping as draft until I add commits for Linux/GCC.

Fix GCC and Clang warnings in MMDevice, MMCore

---

DeviceAdapters/Makefile.am
DeviceAdapters/NotificationTester/DelayedNotifier.h
DeviceAdapters/NotificationTester/Makefile.am
DeviceAdapters/NotificationTester/NotificationTester.cpp
DeviceAdapters/NotificationTester/NotificationTester.vcxproj
DeviceAdapters/NotificationTester/NotificationTester.vcxproj.filters
DeviceAdapters/NotificationTester/ProcessModel.h
DeviceAdapters/configure.ac
micromanager.sln

Pure-software device adapter intended for automated (and interactive) testing of application handling of change notifications.
Initial implementation with property simulator only. Simulation of Z/XY stages, etc., will follow soon.
Draft of docs (to be put on device page once merged):
Device `NTSyncProperty` has `TestProperty` (float) that is never busy (immediately reflects set value). If `NotificationsEnabled` is set to `Yes`, `OnPropertyChanged()` is called from within the property `AfterSet` handler, on the same thread that called into the device adapter.
Device `NTAsyncProperty` has `TestProperty` (float) which distinguishes the target value from the current value, and the current value is slewed toward the target at a constant rate (`SlewTimePerUnit_s`), updating periodically …

Add NotificationTester device adapter

---

DeviceAdapters/QSI/QSI.vcxproj

(I previously forgot to update the Debug to match Release.)

QSI: Use consistent paths in .vcxproj

---

MMCore/MMCore.cpp
MMCore/MMCore.vcxproj
MMCoreJ_wrap/MMCoreJ_wrap.vcxproj
MMDevice/MMDevice-SharedRuntime.vcxproj
MMDevice/MMDevice-StaticRuntime.vcxproj

Remove preprocessor definitions from MMDevice/MMCore/MMCoreJ_wrap .vcxproj files
This is to maintain the cleanup done in #415 (specifically, 4536cc099caa4793fadacbea3dcc694de679f014) -- to prevent the vcxproj build from going out of sync with the experimental Meson build.
- `_DEBUG` - the compiler defines this when using the debug runtime; redundant
- `_LIB` - added by VS by default for static libs; we don't use it
- `_USRDLL` - added by VS by default for DLLs; we don't use it
- `_WINDOWS` - added by VS by default; we don't use it
- `WIN32` - added by VS by default; we prefer `_WIN32`, defined by the compiler
Also delete the single use of `_DEBUG` in `CMMCore::getVersionInfo()`. It is better not to produce a different version string in a debug build, because applications may parse this …

MMDevice/MMCore[J]: Remove unused macro defs

---

MMDevice/MMDevice.h

- Those discussed in #295
- Get/SetModuleHandle(), which were deprecated in comment
- Direct access to device pointers, deprecated in comment
Of these, here are the functions currently used by device adapters on Windows:
```text
DeviceAdapters\FakeCamera\FakeCamera.cpp(461,25): warning C4996: 'MM::Core::GetFocusPosition': was declared deprecated
DeviceAdapters\TwoPhoton\VirtualShutter.cpp(124,46): warning C4996: 'MM::Core::GetSignalIODevice': was declared deprecated
DeviceAdapters\TwoPhoton\VirtualShutter.cpp(132,46): warning C4996: 'MM::Core::GetSignalIODevice': was declared deprecated
DeviceAdapters\TwoPhoton\VirtualShutter.cpp(153,46): warning C4996: 'MM::Core::GetSignalIODevice': was declared deprecated
DeviceAdapters\TwoPhoton\VirtualShutter.cpp(168,46): warning C4996: …
```

MMDevice: Deprecate functions

---

MMDevice/DeviceUtils.cpp
MMDevice/DeviceUtils.h
MMDevice/MMDeviceConstants.h
MMDevice/ModuleInterface.cpp
MMDevice/meson.build
MMDevice/unittest/DeviceUtils-Tests.cpp
MMDevice/unittest/meson.build

That is, remove use of `strcpy()`, `strncpy()`, and `getenv()`.
Replace `str[n]cpy()` with `snprintf()`. Add tests in the case of `CDeviceUtils::CopyLimitedString()` (previous implementation had a bug where it didn't null-terminate if the source string was exactly `MM::MaxStrLength - 1` chars long).
The use of `getenv()` was dead code, so remove entirely.

MMDevice: Remove need for _CRT_SECURE_NO_WARNINGS

---

DeviceAdapters/PrecisExcite/PrecisExcite.cpp

We tried to address a bug in precisExcite.cpp that only allowed to change the last channel of the CoolLED. 
Left debugging output code inside, hoping other people might test it too (see https://forum.image.sc/t/cant-turn-on-coolled-pe-2-from-micromanager-2-0/89702/7). 
This now seems to work with our system.

Bug when controlling CoolLED pE2

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h
DeviceAdapters/Utilities/DAGalvo.cpp
DeviceAdapters/Utilities/Utilities.h

There is ample ambiguity who controls the shutter and channel config while photo-targetting, the UI code or the device adapter.
We should discuss the best path forward, but in the mean time this works.

Galvo projector: adds ability to run polygons to Utilities::DAGalvo device.

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/Utilities/Utilities.h

Did not compile on either Windows or macOS without this.

Fix build after #446

---

DeviceAdapters/Utilities/DAGalvo.cpp

Sorry for the mess, no idea why this was not in the previous PR, it should have been.

Utilities: minor fixes in DAGalvo

---

DeviceAdapters/NIDAQ/NIAnalogOutputPort.cpp
DeviceAdapters/NIDAQ/NIDAQ.cpp
DeviceAdapters/NIDAQ/NIDAQ.h

Also puts the analog output always at the first position when starting a sequence. When the property indicates the transition happens at the end of exposure, we move the first position of the sequence to the end (i.e. move everything else forward by one position).  Works in practice. Default is the old behavior.

Nidaq: adds property indicating whether sequences transitions happen at the beginning or end of exposure

---

MMCore/CoreCallback.cpp

CoreCallback.cpp uses std::min but doesn't include `<algorithm>`, this can cause compile time errors (though I've only seen those errors on Windows)

Add algorithm include  to CoreCallback.cpp

---

DeviceAdapters/Spinnaker/SpinnakerCamera.cpp

Minor add on:
The FLIR cameras have the methods for `ReverseX` and  `ReverseY`, but these were not exposed as properties. One could take care of this through post processing, but for getting proper `live_view` it's useful. 
This was tested on Blackfly and Oryx cameras.

Spinnaker device: Adding the Mirroring X and Y functions

---

DeviceAdapters/NIDAQ/NIAnalogOutputPort.cpp
DeviceAdapters/NIDAQ/NIDAQ.cpp

Also avoids crash when starting a DA sequence of size 0.

NIDAQ: set more logical internal limit for sequence buffer size.

---

DeviceAdapters/Aravis/AravisCamera.cpp
DeviceAdapters/Aravis/AravisCamera.h
DeviceAdapters/Aravis/Makefile.am
DeviceAdapters/Aravis/README.md
DeviceAdapters/Makefile.am
DeviceAdapters/configure.ac

This pull request adds a device adapter for the [Aravis Project](https://github.com/AravisProject) GenICam camera library. 
I'm not sure this pull request is actually ready to go in. I'm opening this pull request now to get some feedback about what else should go into the device adapter and the ways that it does not correctly conform to the MM expected camera behavior.
It has been tested with two different cameras on 64bit linux (a mono FLIR camera and a color Basler camera). It supports mono and RGB images, exposure time and binning.

Aravis (camera) adapter

---

DeviceAdapters/Scientifica/Scientifica.cpp

Fix bug where using the Scientifica device adapter with Motion 2 racks for Y axis moves, move 10 times less than they should.

Fix Scientifica device adapter - Motion 2 Y moves moving incorrect distance

---

DeviceAdapters/PCO_Generic/MicroManager.cpp

Changed MicroManager.cpp in pco_generic device adapter.
FRE

FRE / excelitas pco gmbh / 26.06.2024 / added 48bit RGB

---

DeviceAdapters/ASITiger/ASIPLogic.cpp

Use the RA shortcut for the RDADC serial command. These values are always read even when the "RefreshPropertyValues" property is set to "No". This saves 9 bytes sent per serial command on PLOGIC_16 builds and 12 bytes on PLOGIC_24 builds.

ASITiger: reduce serial traffic for PLogic

---

MMCore/MMCore.cpp
MMCore/MMCore.h

add safeguard to getInstalledDevices to check for device initialization

---

DeviceAdapters/PointGrey/PointGrey.cpp
DeviceAdapters/PointGrey/PointGrey.h

This change exposes the trigger polarity to Micro-Manager (if it exists). The polarity determines whether an external trigger starts an exposure when it is "high" or "low".
Co-authored with @GiorgioTortarolo

Expose trigger polarity to Micro-Manager in Point Grey device adapter

---

MMCore/MMCore.cpp

The check for an initialized hub was already in HubInstance.
@tlambert03 Sorry I missed this while reviewing #476. See
https://github.com/micro-manager/mmCoreAndDevices/blob/36c45e604a6a58dd08427c542881e029d419c5a1/MMCore/Devices/HubInstance.cpp#L36
which is in the code path of `getInstalledDevices()`.
Is it possible that the above check is not functioning (with the `StrictInitializationChecks` feature enabled)? If so, let me know how to reproduce. It should also log a warning with the feature disabled.

Revert pull request #476

---

.github/workflows/ci-mmdevice-mmcore.yml

The macos-11 runner is deprecated and has started to fail.

CI: use macos-12 for the experimental Meson build

---

DeviceAdapters/Zaber/ConnectionManager.cpp
DeviceAdapters/Zaber/FilterCubeTurret.cpp
DeviceAdapters/Zaber/FilterCubeTurret.h
DeviceAdapters/Zaber/FilterWheel.cpp
DeviceAdapters/Zaber/FilterWheel.h
DeviceAdapters/Zaber/Illuminator.cpp
DeviceAdapters/Zaber/Illuminator.h
DeviceAdapters/Zaber/Makefile.am
DeviceAdapters/Zaber/ObjectiveChanger.cpp
DeviceAdapters/Zaber/Stage.cpp
DeviceAdapters/Zaber/Stage.h
DeviceAdapters/Zaber/WdiAutofocus.cpp
DeviceAdapters/Zaber/WdiAutofocus.h
DeviceAdapters/Zaber/XYStage.cpp
DeviceAdapters/Zaber/XYStage.h
DeviceAdapters/Zaber/Zaber.cpp
DeviceAdapters/Zaber/Zaber.h
DeviceAdapters/Zaber/Zaber.vcxproj
DeviceAdapters/Zaber/Zaber.vcxproj.filters
DeviceAdapters/configure.ac

We are adding autofocus support for our Nucleus™️ microscope.
There are also a few general improvements:
- Support for network sharing
- Resetting connection on port change
- Adding `override` to all the API methods
We are also updating to a newer version of our library - 3.4.4. Can we please have SVN updated with our binaries? Please note that the tag.gz contains soft-links. Archive: [https://drive.google.com/file/d/1IisP6pyjYEEDqVsKLyruIEPc5TLhDuW7/view?usp=sharing](https://drive.google.com/file/d/1IisP6pyjYEEDqVsKLyruIEPc5TLhDuW7/view?usp=sharing)
Note: We have tried upgrading our module to C++17 but could not get it working without removing [dynamic exceptions](https://en.cppreference.com/w/cpp/language/except_spec) from some of the base classes.
Thank you. Please let us know if you …

Adding autofocus, general improvements

---

MMDevice/DeviceBase.h
MMDevice/ImageMetadata.h

This allows individual device adapters to be compiled with C++17 (as opposed to our current default of C++14) without encountering warnings or errors due to obsolete [dynamic exception specifications](https://en.cppreference.com/w/cpp/language/except_spec) (which we still keep for use by our SWIG Java bindings).
See #159 for more on C++17 support status.
- Remove pointless `throw ()` from two functions.
- Wrap remaining dynamic exception specifications (2 occurrences) in macro, which expands to nothing unless read by SWIG.
- Removed the warning suppressions related to dynamic exception specifications.
- Confirmed, using japicmp, that the MMCoreJ API did not change (tested with SWIG 3, Linux).
- There is no C++ MMDevice ABI change because dynamic exception specifications are not part of …

MMDevice: Allow compilation with C++17

---

DeviceAdapters/NIDAQ/NIDigitalOutputPort.cpp

NIDAQ: Work around bug with 6341 card that lies about its portWidth.

---

DeviceAdapters/MCL_MicroDrive/MicroDriveZStage.cpp

Fixed a bug that prevented the stage from moving when setting the position of the stage through a device property.

MCL device adapter bug fix. 

---

DeviceAdapters/Utilities/DATTLStateDevice.cpp
DeviceAdapters/Utilities/Utilities.cpp

Without this, the core will change 3.3 to 3.30, resulting in values in configs not matching.  It is unclear where exactly in the core this undesired change in values happens.
Closes #504

Utilities: changed values for TTL Voltage in DA TTL device to 3.30 and 5.00

---

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp
DeviceAdapters/DahengGalaxy/ClassGalaxy.h

Previously, did not report whether a sequence was running.  Also did not implement StartSequencAcquisition with desired number of images as paramater.

Daheng Galaxy: Much better handling of sequence acquisition

---

DeviceAdapters/Arduino/AOTFcontroller/AOTFcontroller.ino
DeviceAdapters/Arduino/Arduino.cpp
DeviceAdapters/Arduino/Arduino.h

Newer firmware (version 3) adds ability to relay max number of sequences supported by the firmware.  DeviceAdapter reads this number (if firmware is version 3 or higher).  This firmware will nor work with older versions of the adapter (which require version 1 or 2, but can easily be hacked to also support version 3).
Closes issue #512

Arduino v3

---

DeviceAdapters/AlliedVisionCamera/AlliedVisionCamera.cpp

This fixes an issue with this device adapter that causes it to fail in some cases, such as when you try and acquire an image time series using pyrco-manager.

Set isSequenceable=false as this is not implemented.

---

MMCore/CoreFeatures.cpp
MMCore/CoreFeatures.h
MMCore/MMCore.cpp
MMCore/MMCore.h

This PR changes the behavior of the Core function initializeAllDevices.  It will discover all device modules contained in the list of devices to be initialized, spin up one thread per module and initialize all requested devices in that module.  This parallelizes device initialization which can improve startup times of the Micro-Manager application considerably.  Tested with a limited number of devices, I will test on a few more microscopes before merging, but requesting review (especially since I am not very experienced writing multi-threaded code in C++) now.
Minor version of Studio was upgraded according to Semver. I will wait for review before merging.

Faster device initialization by multi-threading.

---

DeviceAdapters/OpenCVgrabber/DeviceEnumerator.cpp
DeviceAdapters/OpenCVgrabber/OpenCVgrabber.cpp

uses a pre-initialization property.

OpenCVGrabber: Make it possible to select a specific device,

---

DeviceAdapters/Aravis/AravisCamera.cpp
DeviceAdapters/Basler/BaslerPylonCamera.cpp
DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp
DeviceAdapters/Ximea/XIMEACamera.cpp
MMDevice/MMDevice.h
MMDevice/MMDeviceConstants.h

Add keyword 'g_Keyword_Metadata_Exposure' to replace 'g_Keyword_Meatdata_Exposure'. 
Add comment to indicate that 'g_Keyword_Meatdata_Exposure' is deprecated.
This was discussed in pull request #499.
This keyword does not seem to be widely used. Should it also be propagated to the other camera drivers?

Add keyword 'g_Keyword_Metadata_Exposure'

---

MMCore/MMEventCallback.h

This pull request includes changes to the `MMEventCallback` class in the `MMCore/MMEventCallback.h` file to improve the handling of string parameters in callback methods. The most important change is the modification of the type of the `name` parameter from `char*` to `const char*` in several methods.

make names const in mmeventcallback

---

MMCore/CircularBuffer.cpp
MMCore/MMCore.cpp
MMDevice/MMDeviceConstants.h

`CircularBuffer::InsertMultiChannel` is a pretty important method that populates a `Metadata` object with some pretty critical parameters during sequence acquisition.  That Metadata object is even publicly retrievable using `getLastImageMD`; unfortunately, the keys and values in that object are hardcoded in the source code with un-exposed keywords... making it hard to rely on these values when inspecting metadata.  This PR adds a few new keywords (for "Width", "Height" and all of the pixel types, and ensures that these keywords are used when populating metadata

make all metadata based on keywords in InsertMultiChannel

---

DeviceAdapters/IDSPeak/Changelog.txt
DeviceAdapters/IDSPeak/IDSPeak.cpp
DeviceAdapters/IDSPeak/IDSPeak.h

I've had some comments that the device adapter did not work for some IDS cameras. After thoroughly reading the documentation of those devices, I found that they did not support 8bit mono recording, which I assumed to be universally supported. This version fixes that bug, and adds some additional features.
- Initializes camera to currently active PixelFormat.
- Lets user choose which PixelFormat (eg mono8, or bayerRG10) to record, and which pixelType to convert it to (8bit/16bit/32bitrgba)
- Added support for 10/12bit acquisition by casting it to 16bit (only works for mono, color gets cast to 8bit anyway)

Added support for all PixelFormat and 16bit images

---

DeviceAdapters/NIDAQ/NIAnalogInputPort.cpp
DeviceAdapters/NIDAQ/NIDAQ.cpp
DeviceAdapters/NIDAQ/NIDAQ.h
DeviceAdapters/NIDAQ/NIDAQ.vcxproj
DeviceAdapters/NIDAQ/NIDAQ.vcxproj.filters
DeviceAdapters/NIDAQ/NIDigitalOutputPort.cpp

Expanded the driver to be able to read analog inputs and capture traces. Has been tested with NI MAX emulation software but not with actual hardware.
Things to check before merging:

NIDAQ: Added analog input functionality

---

DeviceAdapters/ArduinoCounter/ArduinoCounter.cpp
DeviceAdapters/ArduinoCounter/ArduinoCounter.h
DeviceAdapters/TeensyPulseGenerator/CameraPulser.cpp
DeviceAdapters/TeensyPulseGenerator/CameraPulser.h
DeviceAdapters/TeensyPulseGenerator/Module.cpp
DeviceAdapters/TeensyPulseGenerator/SingleThread.cpp
DeviceAdapters/TeensyPulseGenerator/SingleThread.h
DeviceAdapters/TeensyPulseGenerator/TeensyCom.cpp
DeviceAdapters/TeensyPulseGenerator/TeensyCom.h
DeviceAdapters/TeensyPulseGenerator/TeensyPulseGenerator.cpp
DeviceAdapters/TeensyPulseGenerator/TeensyPulseGenerator.h
DeviceAdapters/TeensyPulseGenerator/TeensyPulseGenerator.vcxproj
DeviceAdapters/TeensyPulseGenerator/TeensyPulseGenerator.vcxproj.filters
DeviceAdapters/TeensyPulseGenerator/TeensyPulseGenerator/TeensyPulseGenerator.ino
DeviceAdapters/TeensyPulseGenerator/TestTeensyPulseGenerator.py
micromanager.sln

The Teensy firmware can 
- send pulses at defined intervals
- send pulse of defined duration
- send a defined number of pulses or continue until stopped
- optionally wait for an input signal before sending the pulse (after waiting for a defined interval).
The device adapter defines two devices
- A pulse device that allows to set all the Teensy properties and send defined pulses.
- A virtual camera that can be use to trigger the real camera with the Teensy.  
External triggering using the Teensy was tested with the Daheng camera.   Pulse intervals have an sd of ~50ns (although there seems to be a systematic error of about 1 us for 100 ms pulses).  
This firmware and device adapter should allow reliable external triggering of devices and can be a foundation for testing extension of the …

Adds Teensy firmware and corresponding device adapter that can send pulses to an external device (such as a camera)

---

DeviceAdapters/AlliedVisionCamera/AlliedVisionCamera.h

This adds support for Mono 10,12 and 14 bit camera pixel formats. Vimba X converts these to 16 bit images.

Add support for MONO10, MONO12 and MONO14 pixel formats.

---

DeviceAdapters/ASIStage/ASIBase.cpp
DeviceAdapters/ASIStage/ASIBase.h
DeviceAdapters/ASIStage/ASICRISP.cpp
DeviceAdapters/ASIStage/ASILED.cpp
DeviceAdapters/ASIStage/ASIMagnifier.cpp
DeviceAdapters/ASIStage/ASIStateDevice.cpp
DeviceAdapters/ASIStage/ASITIRF.cpp
DeviceAdapters/ASIStage/ASITurret.cpp
DeviceAdapters/ASIStage/ASIXYStage.cpp
DeviceAdapters/ASIStage/ASIXYStage.h
DeviceAdapters/ASIStage/ASIZStage.cpp
DeviceAdapters/ASIStage/ASIZStage.h

On some older microscope systems, I noted that much of the lag in the software is caused by the System updating its cache, which caused the core to ask each device for the value of all of its properties.  The reason for doing is that properties can be changed as a side effect of changing another property, or, more often, there is another interface to the device (such as buttons or a joystick) that also can change these properties.  
Nevertheless, there are also many properties that can be efficiently cached within the device adapter.  If only the device adapter can change these values, and if they do not change as a side effect of changing some other property of the device, then it is fine to read the value of the property on startup and use that cached value (updating the cached value …

ASI Stage: add property caching

---

MMCore/DeviceManager.cpp
MMCore/MMCore.cpp

And improve the error message when attempting to unload "Core" (previously it said no such device).
Closes #564.

MMCore: Disallow loading a device with label Core

---

DeviceAdapters/ZeissCAN/ZeissCAN.cpp
DeviceAdapters/ZeissCAN/ZeissCAN.h

for state and label are send separately.  These results in lengthy communication with the Microscope stand.  By caching the value of the given turret for a specified amount of time (here: 1 second), this PR should speed up the time it takes to update the SystemCache considerably.  Note that the default implementation of GetLabel actually calls the OnState method of the device.

ZeissCAN: when the SystemChache is updated, requests

---

DeviceAdapters/PICAM/PICAMUniversal.cpp
DeviceAdapters/TwainCamera/TwainCamera.cpp
MMDevice/ImageMetadata.h
MMDevice/MMDevice.h

In MMDevice we avoid passing nontrivial C++ objects because they are not always compatible between different types of builds (e.g., MMCore built in Release mode and device adapter built in Debug mode using MSVC). A couple of functions have been violating this rule by passing `ImgBuffer` or `Metadata`. Deprecate these.
Newly deprecate `InsertImage(const Device*, const ImgBuffer&)`.
Newly deprecate `InsertImage(const Device*, const unsigned char*, unsigned, unsigned, unsigned, const Metadata*, bool)`.
Add deprecation warnings for the newly and previously deprecated overloads.
However, **undeprecate** `InsertImage(const Device*, const unsigned char*, unsigned, unsigned, unsigned, const char*, bool)` because it is widely used and reasonable for monochrome-only cameras.
This leaves just 2 …

MMDevice: Depercate unsafe overloads of InsertImage()

---

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp
DeviceAdapters/DahengGalaxy/ClassGalaxy.h

Setting an ROI previously led to a crash (uncaught exception).  Turns out that the camera first has to stop grabbing before one can set the images sizes.  Also fixed a problem with stale width and height that sometimes would cause insertion in the sequence buffer to fail (I am not sure how this CMMError from the circular buffer InsertImage function is handled).
Also cleaned up the code a bit.  Still quite messy.

DahengGalaxy: Fixes bugs in ROI setting

---

MMCore/CoreCallback.h

(Deprecation is formally indicated in the interface class in MMDevice.)

MMCore: Update comment to match deprecation status

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h

For testing, purposes, it would be nice if the XY demo stage didn't immediately return the new commanded stage position.  This PR makes it so that calling `GetPositionSteps` returns a realistic value based on the velocity and the time since the last call to setPositionSteps...  It also exposes velocity as a property.
@marktsuchida, please let me know what you think... haven't compiled and tested yet

Add realistic (non-instantaneous) movement to DemoXYStage position, and expose velocity as property

---

DeviceAdapters/DemoCamera/DemoCamera.h

Introduced in #597 (and mysteriously had no error with MSVC).

DemoCamera: Fix compile error

---

DeviceAdapters/Utilities/ComboXYStage.cpp
DeviceAdapters/Utilities/DATTLStateDevice.cpp
DeviceAdapters/Utilities/MultiCamera.cpp
DeviceAdapters/Utilities/MultiDAStateDevice.cpp
DeviceAdapters/Utilities/MultiShutter.cpp
DeviceAdapters/Utilities/MultiStage.cpp
DeviceAdapters/Utilities/Utilities.cpp

(In the interest of keeping Boost out of our core modules.)
Replace `boost::lexical_cast<std::string>()` with `std::to_string()` (which is exactly equivalent for integer arguments).
Replace `boost::lexical_cast<long>()` with `std::stol()` and handle exceptions accordingly.

Utilities: drop Boost dependency

---

MMCore/Devices/PressurePumpInstance.cpp
MMCore/Devices/PressurePumpInstance.h
MMCore/Devices/VolumetricPumpInstance.cpp
MMCore/Devices/VolumetricPumpInstance.h
MMCore/MMCore.cpp
MMDevice/DeviceBase.h
MMDevice/MMDevice.h

This is a followup to #462.
The device interface version is further bumped 72 -> 73 because the device member functions are renamed to consistently include the units.
Cc: @Lars-Kool.

Pump device fixes

---

MMDevice/DeviceBase.h
MMDevice/MMDevice.h

Another followup to #462.
I think the required/optional distinction got partly lost when the pressure and volumetric pumps were separated. @Lars-Kool Do the changes proposed here correctly capture your intent? Let me know if changes are needed.
(The DeviceBase classes should leave out implementations for required functions, so that device code will get a compile error if the function is not implemented.)

Clarify required/optional functions of pumps

---

micromanager.sln

Best to keep this exactly as saved by Visual Studio, so that we don't get spurious diffs later on (especially because this file often requires merge conflict resolution).

Match micromanager.sln indents to what VS saves

---

DeviceAdapters/ZeissCAN/ZeissCAN.cpp

Since Floats are represented as strings with 4 decimals, we need to define AllowedValues as such.  This API is not very clean....

ZeissCAN: Fix allowedValues for StepSize.

---

DeviceAdapters/Cephla/Squid.h
DeviceAdapters/Cephla/SquidXYStage.cpp
DeviceAdapters/Cephla/SquidZStage.cpp

Should enable using the device adapter with older Cephla stages that use non-standard drive.

Cephla: Adds  pre-init settings to XY and Z stages.

---

DeviceAdapters/Mightex_SB_Cam/Mightex_SB_Cam.vcxproj
DeviceAdapters/Mightex_SB_Cam/Mightex_SB_Cam.vcxproj.filters
DeviceAdapters/Mightex_SB_Cam/Mightex_SB_Camera.cpp
DeviceAdapters/Mightex_SB_Cam/Mightex_SB_Camera.h
micromanager.sln

Dear sir,
We (Mightex systems) add a new camera adapter (Mightex SB-series camera) in a new folder of \Mightex_SB_Cam under the \DeviceAdapters. Please note there're two low level DLLs under  \Mightex_SB_Cam\lib64, these two DLL files have to be at the same dir of the adapter library file.
We didn't do any other modifications to other codes.
There're 3 previous commits which were for another LED driver adapter, but as the project was postponed...the adapter codes weren't added actually.
The product page of the SB cameras is as following:
https://www.mightexsystems.com/product/usb3-0-monochrome-or-color-1-5mp-global-shutter-cmos-camera-8-or-12-bit
The brief description of the SB camera adapter is as following:_
This Micro-Manager adapter can be used to operate Mightex SB-Series Camera. …

Adding a new camera (Mightex SB-series camera) adapter

---

DeviceAdapters/Fluigent/FluigentPressureController.cpp
DeviceAdapters/Fluigent/FluigentPressureController.h

I did this for #616 but somehow forgot to do it for #617.

Fluigent: avoid 'using namespace std'

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.h

currently, stopping the XY demo stage doesn't stop it's virtual motion.

feat: allow demo xy stage to respond to Stop()

---

MMCore/LoadableModules/LoadedDeviceAdapter.cpp

@gselzer pointed out that the error message could be misinterpreted, depending on perspective, so make it clear.

MMCore: Better error message on bad device version

---

MMCore/MMCore.cpp
MMCore/MMCore.h
MMCore/MMEventCallback.h

Closes #594.
I haven't tested this yet.

Always emit `onSystemConfigurationLoaded` when system configuration changed

---

MMCore/ConfigGroup.h
MMCore/MMCore.cpp

They were not correctly updated when
- A config group is created via `defineConfig()` without a call to `defineConfigGroup()`
- All config groups are removed by `unloadAllDevices()`
Also cleaned up some related code.
Closes #631.

MMCore: Keep channel group choices up to date

---

DeviceAdapters/ASIStage/ASIBase.cpp
DeviceAdapters/ASIStage/ASIBase.h
DeviceAdapters/ASIStage/ASICRISP.cpp
DeviceAdapters/ASIStage/ASILED.cpp
DeviceAdapters/ASIStage/ASIMagnifier.cpp
DeviceAdapters/ASIStage/ASIStage.cpp
DeviceAdapters/ASIStage/ASIStage.h
DeviceAdapters/ASIStage/ASIStateDevice.cpp
DeviceAdapters/ASIStage/ASITIRF.cpp
DeviceAdapters/ASIStage/ASITurret.cpp
DeviceAdapters/ASIStage/ASIXYStage.cpp
DeviceAdapters/ASIStage/ASIXYStage.h
DeviceAdapters/ASIStage/ASIZStage.cpp
DeviceAdapters/ASIStage/ASIZStage.h

The MS-2000 set to 19200 baud rate will be detected when you click "Scan Ports" in the Hardware Configuration Wizard.
The advanced properties for saving calibration settings are enabled as a group now (you need all of them for any of them to be useful).
Took care of basic tasks:
- make less copies of `std::string` using overloaded `compare()`
- pass some variables by const reference instead of by value
- simplify `Busy()` functions, etc

ASIStage: support 19200 baud rate in ASIDetectDevice()

---

DeviceAdapters/ASIWPTR/wptr.cpp
DeviceAdapters/ASIWPTR/wptr.h

Format code.
Initialize all variables in constructor of WPFRobot (fixes compiler warning).
Remove use of strcmp. 
Remove use of "using namespace std".
Use compare overload instead of substr.
Use constexpr instead of #define.

ASIwptr: format code, and initialize all variables

---

MMCore/MMCore.cpp

This prevents various issues because arbitrary code in destructors is never a good idea. Also helps with keeping things safe for Python bindings.

MMCore: Disable callback notifications in dtor

---

MMCore/LoadableModules/LoadedDeviceAdapter.cpp
MMCore/LoadableModules/LoadedDeviceAdapter.h
MMCore/LoadableModules/LoadedDeviceAdapterImpl.h
MMCore/LoadableModules/LoadedDeviceAdapterImplMock.cpp
MMCore/LoadableModules/LoadedDeviceAdapterImplMock.h
MMCore/LoadableModules/LoadedDeviceAdapterImplRegular.cpp
MMCore/LoadableModules/LoadedDeviceAdapterImplRegular.h
MMCore/MMCore.cpp
MMCore/MMCore.h
MMCore/MMCore.vcxproj
MMCore/MMCore.vcxproj.filters
MMCore/Makefile.am
MMCore/MockDeviceAdapter.h
MMCore/PluginManager.cpp
MMCore/PluginManager.h
MMCore/meson.build
MMCore/unittest/MockDeviceAdapter-Tests.cpp
MMCore/unittest/meson.build
MMDevice/MMDevice-SharedRuntime.vcxproj
MMDevice/MMDevice-SharedRuntime.vcxproj.filters
MMDevice/MMDevice-StaticRuntime.vcxproj
MMDevice/MMDevice-StaticRuntime.vcxproj.filters
MMDevice/Makefile.am
MMDevice/ModuleInterface.cpp
MMDevice/RegisteredDeviceCollection.h
MMDevice/meson.build
MMDevice/unittest/RegisteredDeviceCollection-Tests.cpp
MMDevice/unittest/meson.build

One of the main reasons we haven't added more unit tests for MMCore has been that most things cannot be tested without loading devices, but using any given device adapter (whether DemoCamera or SequenceTester) is too indirect, inflexible, and fragile.
This PR adds the ability to create ad-hoc, purpose-crafted mock device adapters in C++ unit tests. Tests can directly interact with such self-created mocks to ensure that MMCore is interacting with devices as expected.
There might be future extensions of this that allow testing via (Python/Java) language bindings, etc., but for now, it is a minimum implementation intended only for unit tests written in C++.
TODO:

Mock device adapters for MMCore unit testing

---

DeviceAdapters/CoherentOBIS/CoherentOBIS.cpp
DeviceAdapters/CoherentOBIS/CoherentOBIS.h

Addressing issues described in the following image.sc post: https://forum.image.sc/t/i-cannot-control-coherent-obis-laser-properly-with-micromanager/70937/8.
Using the CoherentOBIS LS/LX laser with micro-manager, the device reports a state of "2" (invalid) and repeatedly reverts to this state. With some testing and packet sniffing, it appears some commands that succeed in PuTTY-- with SYST: or SOUR:-- are sent to the device as SYST1: and SOUR1, causing the device errors and constant switching of states as the device can't be queried.
In the DeviceAdapter, these are hard-coded (SYST1 and SOUR1, with a strange comment "Initialize laser??"), not some enumeration. Fixing the DeviceAdapter and rebuilding with Device Interface 71 (the version our build is using) resolved our errors.

Fixed commands in CoherentOBIS DeviceAdapter.

---

DeviceAdapters/Basler/BaslerPylonCamera.cpp

Instead, leave the SerialNumber choices empty and let Initialize() return the error.
Closes #652.

Basler: Don't throw exception when no camera

---

DeviceAdapters/OpenUC2/Shutter.h
DeviceAdapters/OpenUC2/UC2hub.cpp
DeviceAdapters/OpenUC2/XYStage.h
DeviceAdapters/OpenUC2/ZStage.h
DeviceAdapters/OpenUC2/openUC2.vcxproj
DeviceAdapters/OpenUC2/openUC2.vcxproj.filters
DeviceAdapters/OpenUC2/openuc2.cpp

@beniroquai @marktsuchida 
I was getting build errors that the compiler couldn't find `openUC2.h`.  I noticed that it didn't exist, but `openuc2.h` did (same for .cpp).  I renamed the files and corrected the Makefile accordingly.

Fix OpenUC2 build for case sensitive file systems

---

MMCore/unittest/MockDeviceAdapter-Tests.cpp
MMCore/unittest/MockDeviceUtils.h
MMCore/unittest/PixelSize-Tests.cpp
MMCore/unittest/meson.build

For the benefit of #658.
Adds a convenience class for mock device adapters. We need to further reduce boilerplate for mock devices, but perhaps after we have a few more tests of the same sort.

MMCore: Add tests for pixel size/affine scaling

---

MMCore/MMCore.cpp

if I'm not mistaken, the complex matrix multiplication in `getPixelSizeAffine()` is unnecessary:
assuming a 6-tuple of floats: `[a00, a01, a02, a10, a11, a12]`.  The code reshapes it as
```sh
| a00 a01 a02 |
input = | a10 a11 a12 |
|  0   0   1  |
```
and builds a scaling matrix:
```
| f 0 0 |
scaleM = | 0 f 0 |
| 0 0 1 |
```
and then does the matrix multiplication.  However, because `scaleM` is diagonal,  most of the matrix multiplication is zeros and the only non-zero terms are:
```
scaleM · input = | f·a00 f·a01 f·a02 |
| f·a10 f·a11 f·a12 |
|   0      0     1  |
```
... which, once you throw away the homogenous coordinates again, reduces back down to simply multiplying each value in the original 6-tuple by the scaling factor.
@marktsuchida, please double check

simplify math in getPixelSizeAffine

---

DeviceAdapters/ZeissCAN29/ZeissCAN29.h

Apparently the friend declaration is enough for MSVC but not (Apple) Clang.
Fix for #663.

ZeissCAN29: Clang needs forward declaration

---

MMCore/MMCore.cpp

this fixes #671 
also tackles the `// TODO: more efficient` in all the `set<>Device` methods

fix: fix inconsistency on core XYStage Role, make setting roles more efficient

---

MMCore/MMCore.cpp

found another inconsistency between core properties and core state:
```python
>>> core = CMMCorePlus()
>>> core.loadSystemConfiguration()
>>> core.getProperty('Core', 'Shutter')
'White Light Shutter'
>>> core.unloadDevice('White Light Shutter')
>>> core.getProperty('Core', 'Shutter')
'White Light Shutter'
>>> core = CMMCorePlus()
>>> core.loadSystemConfiguration()
>>> core.getAllowedPropertyValues('Core', 'Shutter')
('', 'LED Shutter', 'White Light Shutter')
>>> core.unloadDevice('LED Shutter')
>>> core.getAllowedPropertyValues('Core', 'Shutter')
('', 'LED Shutter', 'White Light Shutter')
>>> core.setProperty('Core', 'Shutter', 'LED Shutter')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call …
```

Update core properties after unloading a device

---

MMCore/MMCore.cpp
MMCore/MMCore.h
MMCoreJ_wrap/pom.xml

These are more direct than parsing the strings returned by
getVersionInfo() and getAPIVersionInfo(), and do not require
instantiating CMMCore in order to call.
I also considered changing getVersionInfo() and getAPIVersionInfo() to
`static`, which does not break C++ source compatibility. However,
changing a method to static breaks Java binary compatibility (ability to
swap in a newer JAR), so would require bumping the MMCore major version
(since we currently don't have a separate MMCoreJ version number). While
that may not be particularly disruptive, I'm leaving these alone for
now.
(It could get annoying if the very functions to query the version don't work uniformly across versions.)
Closes #681.

MMCore: Add static methods for version numbers

---

.github/workflows/ci-mmdevice-mmcore.yml
MMCore/CircularBuffer.cpp
MMCore/CircularBuffer.h
MMCore/ConfigGroup.h
MMCore/Configuration.cpp
MMCore/Configuration.h
MMCore/Error.h
MMCore/Logging/GenericStreamSink.h
MMCore/MMCore.cpp
MMCore/MMCore.h
MMCoreJ_wrap/MMCoreJ.i

While preserving compatibility with Swig 2/3 for MMCoreJ.
Note that this (probably) won't allow the generated C++ for MMCoreJ to be compiled under C++17.
This is so that the code can be compiled together with other dependencies (nanobind) that require C++17; MMCore code must continue to also compile under C++17.
Closes #682.
Still need to

MMCore: Allow to compile with C++17

---

.github/workflows/sync-components.yml

This syncs MMDevice/ and MMCore/ history to the mmdevice and mmcore repositories, respectively.
Closes #687.

CI: Sync MMDevice and MMCore to mirror repos

---

.github/workflows/ci-mmdevice-mmcore.yml
MMCore/README.md
MMCore/meson.build
MMCore/subprojects/.gitignore
MMCore/subprojects/mmdevice.wrap
MMDevice/README.md
justfile

This allows mmcore (from the mirror repo) to build automatically.
But keep the manual copy for CI and justfile (to use correct version of MMDevice).
The mmdevice.wrap just fetches the latest HEAD. Once MMCore is no longer in mmCoreAndDevices it can point to a specific mmdevice commit, but that would only be confusing if done now when official MMDevice is a cohabitant of mmCoreAndDevices. (The mmdevice commit would never be up to date!)
Also adds READMEs for MMCore and MMDevice.

Add mmdevice.wrap for MMCore Meson build

---

MMCoreJ_wrap/MMCoreJ.i
MMCoreJ_wrap/MMCoreJ_wrap.vcxproj
MMCoreJ_wrap/Makefile.am

Instead, require that the build system provide the correct include path.
(Follow-up of #693)

MMCoreJ: Avoid relative include of MMDevice/MMCore

---

DeviceAdapters/ASIStage/ASIBase.cpp
DeviceAdapters/ASIStage/ASIBase.h
DeviceAdapters/ASIStage/ASICRISP.cpp
DeviceAdapters/ASIStage/ASICRISP.h
DeviceAdapters/ASIStage/ASILED.cpp
DeviceAdapters/ASIStage/ASIMagnifier.cpp
DeviceAdapters/ASIStage/ASIStateDevice.cpp
DeviceAdapters/ASIStage/ASITIRF.cpp
DeviceAdapters/ASIStage/ASITurret.cpp
DeviceAdapters/ASIStage/ASIXYStage.cpp
DeviceAdapters/ASIStage/ASIZStage.cpp

Precompute the serial terminator and command prefix for less branching in `SendCommand` and `QueryCommand`.
Improve `Version` class and add `>=` overload. `ParseVersionString` moved to `Version` class and is now `Version::ParseString`.

ASIStage: precompute protocol for oldstage_, less branching in SendCommand and QueryCommand

---

DeviceAdapters/Revealer/Revealer.vcxproj

This is needed for #588 to work with the current `main`, until #640 is finished.

Temporarily disable SDL Checks for one more device

---

DeviceAdapters/AlliedVisionCamera/AlliedVisionCamera.vcxproj
DeviceAdapters/DahengGalaxy/DahengGalaxy.vcxproj
DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/IDSPeak/IDSPeak.vcxproj
DeviceAdapters/Lumenera/Lumenera.vcxproj
DeviceAdapters/PlayerOne/PlayerOne.vcxproj
DeviceAdapters/PyDevice/PyDevice.vcxproj
DeviceAdapters/QSI/QSI.vcxproj
DeviceAdapters/SequenceTester/SequenceTester.vcxproj
DeviceAdapters/SigmaKoki/SigmaKoki.vcxproj
DeviceAdapters/Spinnaker/SpinnakerCamera.vcxproj
DeviceAdapters/ZWO/ZWO.vcxproj
MMCore/CircularBuffer.cpp
MMCore/CircularBuffer.h
MMCore/CoreCallback.h
MMCore/MMCore.cpp
MMDevice/MMDevice.h

This adds an overwrite mode to the circular buffer, which means that when an image is inserted and there's no more space, it will automatically clear itself. Currently, most cameras do this manually when there is an error on insert. 
This is motivated by the need to deprecate the ability of devices to clear and allocate the buffer in the core. This should instead be done by higher level application code.
One thing I don't fully understand is the `stopOnOverflow` argument of `startSequenceAcquisition`. Some, but not all, cameras appear to have logic that changes behavior based on this flag, but I'm not aware of any higher level code that ever sets this to `false` when running a finite sequence of N frames. 
Regardless, `stopOnOverflow` shouldn't be an issue for merging this, because the …

Automatically clear circular buffer in continuous sequence acquisition

---

MMCore/CoreCallback.cpp
MMCore/CoreCallback.h
MMCore/MMCore.cpp
MMCore/MMCore.h
MMDevice/DeviceBase.h
MMDevice/MMDevice.h

And remove corresponding CoreCallback implementations (and leftover functions from previously deprecated ones).
Closes #295.
This leaves a few deprecated functions in MMDevice because they are still used by a few device adapters:
```cpp
MM_DEPRECATED(virtual int GetFocusPosition(double& pos)) = 0;
MM_DEPRECATED(virtual int GetXYPosition(double& x, double& y)) = 0;
MM_DEPRECATED(virtual MM::SignalIO* GetSignalIODevice(const MM::Device* caller, const char* deviceName)) = 0;
```

MMDevice: Delete most deprecated functions

---

MMCore/MMCore.cpp
MMDevice/MMDeviceConstants.h

This should avoid confusion. No change to MMCore API or behavior.
Technically this requires the Device Interface Version to be bumped,
though none of our devices actually use these constants currently.
Closes #558.

Match MMCore/MMDevice values for focus direction

---

MMCore/CoreCallback.cpp

In #710 (0734eec77f50396a10ecd1a97045f48885edf72b) I changed the signature of one of the two overloads of `InsertImage()` from
```cpp
virtual int InsertImage(
const Device* caller,
const unsigned char* buf,
unsigned width,
unsigned height,
unsigned byteDepth,
const char* serializedMetadata,
const bool doProcess = true) = 0;
```
to
```cpp
virtual int InsertImage(
const Device* caller,
const unsigned char* buf,
unsigned width,
unsigned height,
unsigned byteDepth,
const char* serializedMetadata = nullptr,
const bool doProcess = true) = 0;
```
(added nullptr default argument to `serializedMetadata`).
This was to support existing cameras that were calling the deleted overload
```cpp
MM_DEPRECATED(
virtual int InsertImage(
const Device* caller,
const unsigned char* buf,
unsigned width,
unsigned …
```

Check for null serialized metadata from camera

---

DeviceAdapters/DemoCamera/DemoCamera.cpp
DeviceAdapters/DemoCamera/DemoCamera.vcxproj

Use timeBeginPeriod(1) to improve timing of Sleep call. Links agains Winmm.dll.

DemoCamera: improve timing on Windows in Sequence mode. 

---

DeviceAdapters/SequenceTester/InterDevice.cpp
DeviceAdapters/SequenceTester/InterDevice.h
DeviceAdapters/SequenceTester/LoggedSetting.cpp
DeviceAdapters/SequenceTester/LoggedSetting.h
DeviceAdapters/SequenceTester/Makefile.am
DeviceAdapters/SequenceTester/SequenceTester.cpp
DeviceAdapters/SequenceTester/SequenceTester.h
DeviceAdapters/SequenceTester/SequenceTesterImpl.h
DeviceAdapters/SequenceTester/SettingLogger.cpp
DeviceAdapters/SequenceTester/SettingLogger.h

It still uses Boost.Signals2 and a few little things. But this removes the dependency on Boost.Thread, which requires a library; the remaining usage is header-only.

Reduce Boost usage in SequenceTester

---

MMCore/subprojects/catch2.wrap
MMDevice/subprojects/catch2.wrap
justfile

Also make sure `just clean` removes Catch2, since Meson doesn't replace subproject directories once they exist.

Meson: Upgrade Catch2 wrap

---

MMCore/meson.build

This does to MMCore what #735 did to MMDevice (sorry for the churn).
We currently build MMCore only as a static library (never shared library/DLL on its own), but the primary use case is to build it into a shared library (Python or Java extension). It is almost never the case that a shared library wants to expose the MMCore C++ API to its clients. So this is a good default.
If we (in the future) add support for building MMCore as a C++ shared library, this is still a good setting, because then each public API function should be explicitly exported (as it will have to be on Windows anyway).
In particular, this removes the unnecessary exported symbols from pymmcore builds without the pymmcore build script having to jump through hoops.

Meson: MMCore: default to hidden visibility

---

DeviceAdapters/Utilities/Makefile.am
DeviceAdapters/Utilities/PropertyShutter.cpp
DeviceAdapters/Utilities/Utilities.cpp
DeviceAdapters/Utilities/Utilities.h
DeviceAdapters/Utilities/Utilities.vcxproj
DeviceAdapters/Utilities/Utilities.vcxproj.filters

This pull request introduces a new `PropertyShutter` utility device that can control any device property, not just digital-to-analog outputs as in `DAShutter` with Arduinos and NIDAQs. It allows using sliders or other properties as shutters, for example a halogen lamp that has only a voltage slider and no explicit on/off property. This makes it possible to use such devices as shutters in multi-dimensional acquisitions. The PropertyShutter is highly configurable, and the following properties can be set:
- Target Device & Property: which property the PropertyShutter will change
- Open & Closed Values: values to apply when the shutter is opened/closed
- Shutter Delay: optional delay after opening or closing
- Invert Logic: invert open/closed values if needed
- State: useful for debugging, …

Add PropertyShutter utility device

---

DeviceAdapters/JAI/JAI.vcxproj

The previous verison used was 5.1.3.
This will require users to install 6.x (at the very least).

JAI: Upgrade eBUS-SDK to 6.5.3

---

DeviceAdapters/CairnOptoSpinUCSF/CairnOptoSpinUCSF.cpp
DeviceAdapters/CairnOptoSpinUCSF/CairnOptoSpinUCSF.h

Make device and property names identical to Cairn device adapter.
Except for Spinning the filter wheel (not sure who uses that), this should be a one to one drop in replacement for the Cairn adapter.

Cairn optospin UCSF

---

MMDevice/DeviceThreads.h

PTHREAD_MUTEX_RECURSIVE (without the _NP "non-portable") has been available on Linux (glibc) since around the beginning of this century, I think.

MMDevice: Remove use of obsolete pthread attr name
