MMCorePy_wrap/MMCorePy.i
Transplanted from micro-manager/micro-manager#1157 by @tlambert03.
I will merge this shortly after a final review of exception types.
=> Fix pymmcore error messages

DeviceAdapters/PrizmatixDevice/PrizmatixDevice.vcxproj, DeviceAdapters/PrizmatixDevice/PrizmatixDevice.vcxproj.filters, DeviceAdapters/PrizmatixDevice/PrizmatixMain.cpp, DeviceAdapters/PrizmatixDevice/PrizmatixMain.h, micromanager.sln
Driver for Prizmatix LED Light Sources for Fluorescence Microscope
=> Prizmztix device mm

DeviceAdapters/SerialManager/SerialManager.cpp
Closes https://github.com/micro-manager/micro-manager/issues/1254.
With serial devices using FTDI USB-serial chips, reloading a config file
would fail stochastically. (Probably this would not be seen with a
config file containing more than 1 or 2 devices.)
Win32 API call tracing showed that the port and related resources are
correctly closed, so added an extra sleep after joining the async
thread, which eliminated the problem in my testing. Sleeps are 2x the
minimum I found needed in testing, to account for system variability.
=> Protect against serial port reopening failure

DeviceAdapters/ASITiger/ASIPLogic.cpp, DeviceAdapters/ASITiger/ASITiger.h
mirrors changes committed to SVN repo 2021-07-24
=> ASITiger PLC support presets 55-59

DeviceAdapters/Andor/Andor.cpp, DeviceAdapters/Andor/Andor.h
Added initial USB iStar gating features to Andor adapter.
=> Andor: added USB iStar features

DeviceAdapters/Makefile.am
delete repeated Diskovery item and keep in alphabetic order
=> delete repeated Diskovery item

DeviceAdapters/ASIStage/ASIStage.cpp, DeviceAdapters/ASIStage/ASIStage.h
Added build name, compile date, and version properties to all devices for ASIStage.
=> ASIStage: added more device properties

MMCore/CoreCallback.cpp, MMCore/LibraryInfo/LibraryPathsUnix.cpp, MMCore/MMCore.cpp, MMDevice/Property.cpp
As seen during pymmcore build.
=> Fix GCC warnings on Linux

DeviceAdapters/AndorSDK3/EventsManager.cpp
Fix for Andor cameras using CXP events.
=> Andor cxp event fix

DeviceAdapters/ASITiger/ASICRISP.cpp
The wrong serial command was being sent to the controller.
=> ASITiger: fix GainMultiplier property for CRISP

DeviceAdapters/ASIStage/ASIStage.cpp
The wrong serial command was being sent to the controller.
=> ASIStage: fix GainMultiplier property for CRISP

DeviceAdapters/Motic/MoticCamera.cpp
If correct, closes #81.  Needs testing.
=> Motic: Convert Motic binning to MM binning, hopefully correctly

micromanager.sln
=> Re-enable BDPathway in Release build

DeviceAdapters/Spinnaker/SpinnakerCamera.vcxproj
change spinnaker to use vs2015 sdk. No need for a change to the SVN repo
=> change spinnaker to use vs2015 sdk

DeviceAdapters/NewportCONEX/NewportCONEX.vcxproj, DeviceAdapters/ObjectiveImaging/OasisControl.cpp, DeviceAdapters/TUCam/MMTUCam.vcxproj, DeviceAdapters/ThorlabsDCxxxx/ThorlabsDCxxxx.vcxproj, DeviceAdapters/ZeissAxioZoom/ZeissMonitor.cpp
This PR fixes a few projects that build find in "Release" mode but not in "Debug". There are still a few projects remaining, the "Mightex" and "Mightex_BLS" are the main ones that I'm not sure what the issue is.
=> Debug build fixes

DeviceAdapters/WieneckeSinske/ZPiezoCanDevice.cpp
=> Fix capitalization of #included file

DeviceAdapters/PointGrey/PointGrey.vcxproj
Addresses #130.  Uses SDK v 2.13.3.61.
=> Point Grey: Made it compile with SDK v2.13.3.61 using v140 toolset.

DeviceAdapters/HIDManager/HIDManager.vcxproj
Uses hidapi-0.11.2 very recently added to 3rdpartypublic.
=> HIDManager: build using hidapi 0.11.2

DeviceAdapters/ASITiger/ASIDac.cpp, DeviceAdapters/ASITiger/ASIXYStage.h
Also fixed a broken link in ASIXYStage.h
=> ASITiger: initialize variables in constructor in ASIDac.cpp

DeviceAdapters/HIDManager/build.xml
Addresses the remaining bit of #129.
=> Update hidapi DLL install to match build

DeviceAdapters/IDS_uEye/IDS_uEye.cpp
IDS uEye cameras limit ROI positions and sizes to certain increments, e.g. multiples of 8 in width and 2 in height for UI-3060 cameras. There is also a minimal size for ROIs.
The current device adapter does not check for supported ROI position, and (in our testing) sending unsupported positions is silently ignored (i.e. corrected to a nearby supported position) by the camera. **This yields incorrect **metadata**, which we notice when using e.g. pixel-based image corrections.
The pull request reworks the SetROI(...) call to send only supported ROI sizes and positions to the camera.
=> IDS_uEye: updated ROI position calculation

DeviceAdapters/ASITiger/ASIDac.cpp, DeviceAdapters/ASITiger/ASIXYStage.h, DeviceAdapters/IDS_uEye/IDS_uEye.cpp, DeviceAdapters/IDS_uEye/IDS_uEye.h, DeviceAdapters/IDS_uEye/IDS_uEye.vcxproj, DeviceAdapters/PCO_Generic/MicroManager.cpp, DeviceAdapters/PCO_Generic/readme.txt, DeviceAdapters/PicardStage/PicardStage.cpp, DeviceAdapters/XCiteXT600/XT600Dev.cpp
This brings `vs2019` up to date with code changes in `main`.
=> Merge main into vs2019

DeviceAdapters/ASITiger/ASIDacXYStage.cpp, DeviceAdapters/ASITiger/ASIDacXYStage.h, DeviceAdapters/ASITiger/ASITiger.cpp, DeviceAdapters/ASITiger/ASITiger.h, DeviceAdapters/ASITiger/ASITiger.vcxproj, DeviceAdapters/ASITiger/ASITiger.vcxproj.filters, DeviceAdapters/ASITiger/ASITigerComm.cpp, DeviceAdapters/ASITiger/Makefile.am
This adds functionality for the DAC_XY_4CH firmware build.
=> Add new DACXYStage device to ASITiger

DeviceAdapters/configure.ac, m4/ax_cxx_compile_stdcxx.m4
=> Autoconf: require, and default to, C++14

DeviceAdapters/SutterLambda/SutterLambda.cpp, DeviceAdapters/SutterLambda/SutterLambda.h, DeviceAdapters/SutterLambda/SutterLambda.vcxproj
Add support for Sutter Lambda 721 multi-LED light source as a Shutter device.
Allows single LED mode (same as a filter wheel), and multi-LED mode allowing up to 7 LEDs activated.  Also provides individual power % level.
=> Add support for Sutter Lambda 721

DeviceAdapters/SutterLambda/SutterLambda.cpp
I removed the unused Wheel device for the 721.  id=3 is not needed either.  Thanks!
=> Remove unused Wheel device

DeviceAdapters/RaptorEPIX/HoribaEPIX.vcxproj, DeviceAdapters/RaptorEPIX/RaptorEPIX.cpp, DeviceAdapters/RaptorEPIX/RaptorEPIX.vcxproj, DeviceAdapters/RaptorEPIX/XCAP/xcapRaptorEagleXO4240_Linux64.fmt, DeviceAdapters/RaptorEPIX/XCAP/xcapRaptorEagleXO4240_Linux64_Bin1.fmt, DeviceAdapters/RaptorEPIX/XCAP/xcapRaptorNinox-640_64C.fmt, DeviceAdapters/RaptorEPIX/XCAP/xcapRaptorNinox-640_64C_Bin1.fmt, DeviceAdapters/RaptorEPIX/build.xml
Also fixes various compiler warnings.
=> Update RaptorEPIX to support latest EPIX library

micromanager.sln
Add the new projects from #200 and #201 to the solution.
=> Add Dragonfly and IntegratedLaserEngine to build

DeviceAdapters/TUCam/MMTUCam.cpp, DeviceAdapters/TUCam/MMTUCam.h
1.Update MMTUCam.cpp and  MMTUCam.h
=> Update TUCam Plugin in

DeviceAdapters/TUCam/MMTUCam.vcxproj
=> Use new TUCam SDK

DeviceAdapters/Spinnaker/SpinnakerCamera.cpp
=> fix ROI increment bug

DeviceAdapters/Spinnaker/SpinnakerCamera.cpp, DeviceAdapters/Spinnaker/SpinnakerCamera.h
See : https://forum.image.sc/t/flir-chameleon3-camera-problem-with-transpose-and-mda/69955/9
=> Spinnaker: Binning returns 1 for Video Mode cameras

DeviceAdapters/Thorlabs_ELL14/ELL14.cpp, DeviceAdapters/Thorlabs_ELL14/ELL14.h, DeviceAdapters/Thorlabs_ELL14/Thorlabs_ELL14.vcxproj, DeviceAdapters/Thorlabs_ELL14/Thorlabs_ELL14.vcxproj.filters, micromanager.sln
Add new Device Adapter for the Throlabs' ELL14.
=> Added device adapter for the ELL14

DeviceAdapters/ETL/ETL.vcxproj, DeviceAdapters/ETL/ETL.vcxproj.filters, DeviceAdapters/ETL/myETL.cpp, DeviceAdapters/ETL/myETL.h
allows you to change the current by accessing the corresponding property.
In progress ...
=> Optotune Tunable Lens driver

DeviceAdapters/ASITiger/ASIHub.h, DeviceAdapters/ASITiger/ASILED.cpp, DeviceAdapters/ASITiger/ASITigerComm.cpp
Also add support for detecting the build name TGLED_S as stabilight, it was TGLEDS before.
=> ASITiger: fix bug in stabilight so it detects all channels and add support for TGLED_S build name

DeviceAdapters/Thorlabs_ELL14/ELL14.cpp, DeviceAdapters/Thorlabs_ELL14/license.txt
New pull request to add the Device Adapter Thorlabs_ELL14 with the licence
=> Working branch

DeviceAdapters/LightSheetManager/LightSheetDeviceManager.cpp, DeviceAdapters/LightSheetManager/LightSheetDeviceManager.h, DeviceAdapters/LightSheetManager/LightSheetManager.cpp, DeviceAdapters/LightSheetManager/LightSheetManager.h, DeviceAdapters/LightSheetManager/LightSheetManager.vcxproj, DeviceAdapters/LightSheetManager/LightSheetManager.vcxproj.filters, DeviceAdapters/LightSheetManager/Makefile.am, DeviceAdapters/LightSheetManager/MicroscopeGeometry.cpp, DeviceAdapters/LightSheetManager/MicroscopeGeometry.h, DeviceAdapters/LightSheetManager/license.txt, micromanager.sln
This is the device adapter for the LightSheetManager plugin, it maps physical devices to their logical names in the plugin.
=> Device Adapter for LightSheetManager

DeviceAdapters/XCite120PC_Exacte/XCite.cpp
=> Mention X-Cite XYLIS in device description

DeviceAdapters/TriggerScope/TriggerScope.cpp, DeviceAdapters/TriggerScope/TriggerScope.h
Fix a missing include on macOS.
Fix warnings on macOS.
=> TriggerScope includes and warnings

DeviceAdapters/ASITiger/ASICRISP.cpp
This is the max value in the firmware.
=> ASITiger: "Number of Averages" max value is 8

MMCore/PluginManager.cpp
Issue manifested after changing other includes.
=> MMCore: Supply a missing include

DeviceAdapters/Makefile.am, DeviceAdapters/MicroFPGA/Makefile.am, DeviceAdapters/MicroFPGA/MicroFPGA.vcxproj, DeviceAdapters/configure.ac, micromanager.sln
=> Add MicroFPGA to build

DeviceAdapters/LaserQuantumLaser/LaserQuantumLaser.vcxproj.filters, DeviceAdapters/SmarActHCU-3D/SmarActHCU-3D.vcxproj.filters, DeviceAdapters/ThorlabsElliptecSlider/ThorlabsElliptecSlider.vcxproj.filters, DeviceAdapters/Toptica_iBeamSmartCW/Toptica_iBeamSmartCW.vcxproj.filters
Add the vcxproj.filters files for the following DeviceAdapters:
- LaserQuantumLaser
- SmarAct stage
- Toptica iBeamSmart
- Thorlabs ElliptecSlider 
linked to discussion in https://github.com/micro-manager/mmCoreAndDevices/issues/207
=> add vcxproj.filters

DeviceAdapters/PI_GCS_2/PIGCSCommandsDLL.cpp
=> PI_GCS_2: Fix compilation on Linux

DeviceAdapters/MeadowlarkLC/MeadowlarkLC.vcxproj.filters
=> Add MeadowlarkLC.vcxproj.filters

DeviceAdapters/Atik/Atik.cpp, DeviceAdapters/Atik/Atik.h, DeviceAdapters/Atik/AtikCamerasSDK.cpp, DeviceAdapters/Atik/AtikMMCamera.vcxproj, DeviceAdapters/Atik/AtikMMCamera.vcxproj.filters, DeviceAdapters/Atik/SequenceThread.cpp, DeviceAdapters/Atik/license.txt, micromanager.sln
Hi, hopefully I've got most things correct here.
You'll need AtikCameras.h, AtikDefs.h & AtikCameras.cpp from our sdk which can be found on the second tab [here](https://www.atik-cameras.com/software-downloads/). 
End users will need to install our drivers and use the 4 dlls from lib/win/64.
Please let me know if I've messed up at all and myself or one of the team will fix asap.
=> Atik Cameras MM device adapter

DeviceAdapters/MPBLaser/MPBLaser.h, DeviceAdapters/MPBLaser/MPBLaser.vcxproj, DeviceAdapters/MPBLaser/MPBLaser.vcxproj.filters, DeviceAdapters/MPBLaser/Makefile.am, DeviceAdapters/Makefile.am, DeviceAdapters/configure.ac, micromanager.sln
See micro-manager/micro-manager#615.
Closes #207.
=> Add MPBLaser to build

DeviceAdapters/Atik/Atik.cpp, DeviceAdapters/Atik/Atik.h
Added functionality to set the Exposure Mode.
Added functionality to read sensor temperature.
Now loading the cameras settings correctly during init.
=> Atik Cameras MM update

MMCoreJ_wrap/pom.xml
In the future, the MMCore.cpp and pom.xml (in MMcoreJ) should be kept at the same value. It would be nice if this could be automated.  Ready to be pushed to maven on a system that has the PGP keys installed correctly.
=> Updates pom.xml to version 10.4.0.  

DeviceAdapters/Zaber/ObjectiveChanger.cpp
It's an unfortunate quality issue.
Thank you.
=> Fixing property name.

DeviceAdapters/Zaber/ObjectiveChanger.cpp
We have found some issues with our implementation. We are making sure that the device moves only if there are changes.
Thank you.
=> Fixing objective changer.

DeviceAdapters/ArduinoCounter/ArduinoCounter.cpp, DeviceAdapters/ArduinoCounter/ArduinoCounter.h, DeviceAdapters/ArduinoCounter/ArduinoCounter/ArduinoCounter.ino
=> Arduino counter, adds option to invert output

MMCoreJ_wrap/pom.xml
=> Update MMCoreJ version to match MMCore

DeviceAdapters/Dragonfly/build.xml
=> Add Andor Dragonfly DLL to Windows install

MMCoreJ_wrap/Makefile.am
=> Fix Automake build of MMCoreJ

DeviceAdapters/HIDManager/HIDManager.cpp
closes #402
@nicost, i believe you wrote the HID manager ... can you review this one and confirm whether it would be OK to remove these print statements?
=> Remove printf statements during HID device init

MMCore/MMCore.h, MMCore/meson.build
And some minor cleanup that is inconsequential at the moment.
=> Remove unused #include in MMCore

DeviceAdapters/SequenceTester/SettingLogger.cpp, DeviceAdapters/SequenceTester/SettingLogger.h, DeviceAdapters/SequenceTester/TextImage.cpp, DeviceAdapters/SequenceTester/TextImage.h
Replace tiny proportional font with larger monospace font.
=> SequenceTester: Use more readable text rendering

DeviceAdapters/TUCam/MMTUCam.cpp, DeviceAdapters/TUCam/MMTUCam.h
support aries 16 lt/fl 9bw/fl 26bw
=> support new camera

DeviceAdapters/TUCam/MMTUCam.cpp, DeviceAdapters/TUCam/MMTUCam.h
=> Revert #429 (TUCam)

DeviceAdapters/TUCam/MMTUCam.cpp, DeviceAdapters/TUCam/MMTUCam.h, DeviceAdapters/TUCam/MMTUCam.vcxproj
This PR includes the same commits as #429 (which was once reverted in #430), rebased onto `main`, plus an additional commit to update the TUCam SDK version in the build.
=> TUCam update

MMCore/meson.build, MMCore/meson_options.txt, MMCore/unittest/meson.build, MMDevice/meson.build, MMDevice/meson_options.txt, MMDevice/unittest/meson.build
See individual commits. Changes motivated by https://github.com/micro-manager/pymmcore/pull/109.
=> Misc fixes to MMDevice/MMCore Meson build files

DeviceAdapters/IDSPeak/Changelog.txt, DeviceAdapters/IDSPeak/IDSPeak.cpp, DeviceAdapters/IDSPeak/IDSPeak.h, DeviceAdapters/IDSPeak/README.md
Hi Mark,
After reading the comments on the image.sc forum. I took a look into multi-camera setups, and made the IDS camera device adapter compatible with the Utilities->multi camera adapter.
Best,
Lars
=> Made Device Adapter compatible with the multi-camera utility

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp, DeviceAdapters/DahengGalaxy/ClassGalaxy.h, DeviceAdapters/DahengGalaxy/DahengGalaxy.vcxproj, DeviceAdapters/DahengGalaxy/DahengGalaxy.vcxproj.filters, DeviceAdapters/DahengGalaxy/GalaxySDK.props, micromanager.sln
(which was basedon the BaslerPylon adapter code).  
Daheng grants free re-distribtion of their SDK to support building this code.  Relevant files have been added to 3rdpartypublic.
=> DahengGalaxy: based on code from Daheng 

DeviceAdapters/Hikrobot/Hikrobot.vcxproj, DeviceAdapters/Hikrobot/HikrobotCamera.cpp, DeviceAdapters/Hikrobot/HikrobotCamera.h, DeviceAdapters/Hikrobot/MvCamera.cpp, DeviceAdapters/Hikrobot/MvCamera.h, micromanager.sln
a plugin to support hikrobot industry cameras.
=> Add hikrobot camera plugin

DeviceAdapters/ASITiger/ASIPLogic.cpp, DeviceAdapters/ASITiger/ASIPLogic.h, DeviceAdapters/ASITiger/ASITiger.h, DeviceAdapters/ASITiger/ASIXYStage.cpp, DeviceAdapters/ASITiger/ASIZStage.cpp
Adds the 7-channel TTL shutter mode and initializes some advanced properties, ports from the 1.4 Device Adapter.
=> ASITiger: add seven channel TTL shutter mode and init advanced props

DeviceAdapters/TUCam/MMTUCam.cpp, DeviceAdapters/TUCam/MMTUCam.h
Update the latest plugins 20240821
=> Update  TUCam Plugin

DeviceAdapters/ASITiger/ASIScanner.cpp
Cc: @bls337, in case you want to re-check this code.
=> ASITiger: fix missing semicolon

DeviceAdapters/ScientificaMotion8/ScientificaMotion8.cpp, DeviceAdapters/ScientificaMotion8/ScientificaMotion8.h, DeviceAdapters/ScientificaMotion8/ScientificaMotion8.vcxproj, DeviceAdapters/ScientificaMotion8/ScientificaMotion8.vcxproj.filters, DeviceAdapters/ScientificaMotion8/ScientificaRxPacket.cpp, DeviceAdapters/ScientificaMotion8/ScientificaRxPacket.h, DeviceAdapters/ScientificaMotion8/ScientificaTxPacket.cpp, DeviceAdapters/ScientificaMotion8/ScientificaTxPacket.h, micromanager.sln
The existing Scientifica driver does not support the racks Scientifica now sell.
=> Add Scientifica Motion 8 device adapter

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp, DeviceAdapters/DahengGalaxy/ClassGalaxy.h
External control was not tested, but also should work.  Added ExposureTimeoutSeconds property that should be helpful for external control.
=> DahengGalaxy adapter:  Adds UserOutputSelector and support for Software control

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp, DeviceAdapters/DahengGalaxy/ClassGalaxy.h
Should be able to operate the camera in external trigger code and get a Frame related output from the device.
=> Daheng: added LineMode and LineSource properties

DeviceAdapters/DahengGalaxy/ClassGalaxy.cpp
=> Daheng: Made binning work as expected.

DeviceAdapters/Elveflow/Elveflow.vcxproj, DeviceAdapters/Elveflow/Elveflow.vcxproj.filters, DeviceAdapters/Elveflow/elveflow_device.cpp, DeviceAdapters/Elveflow/mux_distrib.cpp, DeviceAdapters/Elveflow/mux_distrib.h, DeviceAdapters/Elveflow/mux_wire_v3.cpp, DeviceAdapters/Elveflow/mux_wire_v3.h, DeviceAdapters/Elveflow/ob1_mk4.cpp, DeviceAdapters/Elveflow/ob1_mk4.h, micromanager.sln
- Implementation of device communication protocols to manage multiple devices of Elveflow (Ob1Mk4, MuxWirev3, MuxDistrib).
- Compatibility adjustments to ensure smooth operation across supported devices.
- Thorough testing to verify synchronization and performance when working with three devices concurrently.
=> Add Support for Controlling Three Elveflow's Devices in Micro-Manager

DeviceAdapters/Elveflow/license.txt
As per https://github.com/micro-manager/mmCoreAndDevices/pull/553#issuecomment-2633593884
Cc: @Vroouum
=> Add BSD license for Elveflow

MMCore/ConfigGroup.h, MMCore/MMCore.cpp, MMCore/MMCore.h, MMDevice/MMDeviceConstants.h
See issues:
- https://github.com/micro-manager/micro-manager/issues/1984
- https://github.com/micro-manager/micro-manager/issues/2038
=> Core: Adds functions to get and set dxdz, dydz and optionalZ in pixel size conifgurations.

DeviceAdapters/ASIStage/ASIXYStage.cpp
VectorMove could also be cached (but I did not do that yet).
=> ASIStage: Fix bugs in acceleration code. 

DeviceAdapters/ASIStage/ASIXYStage.cpp
First check whether this is a special controller (CheckDeviceStatus is not a well named function).
=> ASIStage: Hopefully fix issues with LX4000.

DeviceAdapters/CSUW1/CSUW1.cpp, DeviceAdapters/CSUW1/CSUW1.h
Should speed up operation of W1 considerably.
=> W1: cache properties rather than enquire every time again.

DeviceAdapters/CSUW1/CSUW1.cpp, DeviceAdapters/CSUW1/CSUW1.h, DeviceAdapters/NewportCONEX/Conex_Axis.cpp, DeviceAdapters/NewportCONEX/Conex_Axis.h
Also simplified the code a bit, there was a lot of duplication.  It is still unclear why there were 3 devices: all code paths seemed identical.  Hope I did not oversee something.d
=> Newport CONEX: Adds properties for position, lower and upper limit, speed and acceleration

MMCore/MMCore.cpp
File name, and whether parallel is enabled or not.
=> MMCore: additional logging when loading cfg file

DeviceAdapters/IDSPeak/Changelog.txt, DeviceAdapters/IDSPeak/IDSPeak.cpp, DeviceAdapters/IDSPeak/IDSPeak.h
Hi @nicost and @marktsuchida,
I've updated the device adapter for IDS cameras. It now makes certain features optional (like analog/digital gain and auto whitebalance), such that cameras that don't support these features no longer crash.
Best,
Lars
=> IDS device adapter

micromanager.sln
This should reduce diff noise, since Visual Studio makes these changes when a change is made to the sln file.
=> Normalize case in VS solution file

DeviceAdapters/AMF/AMF.vcxproj, DeviceAdapters/AMF/AMF.vcxproj.filters, DeviceAdapters/AMF/AMF_Commands.h, DeviceAdapters/AMF/AMF_Hub.cpp, DeviceAdapters/AMF/AMF_Hub.h, DeviceAdapters/AMF/AMF_RVM.cpp, DeviceAdapters/AMF/AMF_RVM.h, micromanager.sln
Hi @marktsuchida & @nicost,
I recently developed a device adapter for Advanced Microfluidics valves. Would be great if you could include this.
Best,
Lars
=> Device Adapter AMF valves

DeviceAdapters/Revealer/LICENSE, DeviceAdapters/Revealer/MMSCCam.cpp, DeviceAdapters/Revealer/MMSCCam.h, DeviceAdapters/Revealer/Revealer.vcxproj, DeviceAdapters/Revealer/Revealer.vcxproj.filters, DeviceAdapters/Revealer/framework.h, micromanager.sln
This is a revised version of #536.
Compared to #536,
- Rebased on the current `main` branch
- Changed license to LGPL
- Placed dependencies (SDK) in our private repo and updated paths in project (the SDK files are therefore removed from this pull request)
- Made some additional minor edits (see commit messages)
@Ryanyntc2013 and @cxylh can you please review this version and make sure everything is right? Once you are okay with it, it is ready to merge.
=> Add Revealer scientific camera (revised)

DeviceAdapters/VisiTech_iSIM/VTiSIM.cpp, DeviceAdapters/VisiTech_iSIM/VTiSIM.h, DeviceAdapters/VisiTech_iSIM/VisiTech_iSIM.vcxproj
Needs newer SDK (2.9.2) which is in 3rdparty.
=> Visitech iSIM: several years of changes by Visitech

DeviceAdapters/ASIStage/ASIBase.cpp, DeviceAdapters/ASIStage/ASIBase.h, DeviceAdapters/ASIStage/ASICRISP.cpp, DeviceAdapters/ASIStage/ASICRISP.h, DeviceAdapters/ASIStage/ASIStage.cpp, DeviceAdapters/ASIStage/ASIStage.h
Use MM::ActionLambda to consolidate Sum and Dither Error.
Fix for IsVersionAtLeast.
=> ASIStage: fix IsVersionAtLeast function

DeviceAdapters/OpenUC2/LICENSE, DeviceAdapters/OpenUC2/Shutter.cpp, DeviceAdapters/OpenUC2/Shutter.h, DeviceAdapters/OpenUC2/UC2Hub.h, DeviceAdapters/OpenUC2/UC2hub.cpp, DeviceAdapters/OpenUC2/XYStage.cpp, DeviceAdapters/OpenUC2/XYStage.h, DeviceAdapters/OpenUC2/ZStage.cpp, DeviceAdapters/OpenUC2/ZStage.h, DeviceAdapters/OpenUC2/openUC2.vcxproj, DeviceAdapters/OpenUC2/openUC2.vcxproj.filters, DeviceAdapters/OpenUC2/openuc2.cpp, DeviceAdapters/OpenUC2/openuc2.h
This adds the UC2-ESP32 based firmware devices to micromanager. Features:
- Controlling Steppers connected to Dir/Stp interface
- Control Lasers/LEDs via TTL/PWM 
For more information and firmware download, please visit https://youseetoo.github.io/
=> Adding openUC2 Device Adapater

DeviceAdapters/Makefile.am, DeviceAdapters/OpenUC2/Makefile.am, DeviceAdapters/OpenUC2/openUC2.vcxproj, DeviceAdapters/configure.ac, micromanager.sln
=> Add openUC2 to build

DeviceAdapters/ASITiger/ASIScanner.cpp
this matches documentation and usage by Projector plugin
=> ASITiger: SetSpotInterval no longer actually sets interval but only exposure time

DeviceAdapters/Arduino/AOTFController_Teensy35_36/AOTFController_Teensy35_36.ino, DeviceAdapters/Arduino/Arduino.cpp, DeviceAdapters/Arduino/Arduino.h
This firmware is compatible with the existing Arduino device adpater.
=> Arduino32 firmware, works on Teensy 3.5.

DeviceAdapters/AndorSDK3/AOIProperty.cpp, DeviceAdapters/AndorSDK3/AOIProperty.h, DeviceAdapters/AndorSDK3/AndorSDK3.cpp, DeviceAdapters/AndorSDK3/AndorSDK3.h, DeviceAdapters/AndorSDK3/AndorSDK3.vcxproj, DeviceAdapters/AndorSDK3/AndorSDK3.vcxproj.filters, DeviceAdapters/AndorSDK3/AndorSDK3Strings.h, DeviceAdapters/AndorSDK3/BooleanProperty.h, DeviceAdapters/AndorSDK3/EnumProperty.cpp, DeviceAdapters/AndorSDK3/EnumProperty.h, DeviceAdapters/AndorSDK3/ExposureProperty.h, DeviceAdapters/AndorSDK3/FloatProperty.cpp, DeviceAdapters/AndorSDK3/FloatProperty.h, DeviceAdapters/AndorSDK3/IProperty.h, DeviceAdapters/AndorSDK3/IntegerProperty.cpp, DeviceAdapters/AndorSDK3/IntegerProperty.h, DeviceAdapters/AndorSDK3/Makefile.am, DeviceAdapters/AndorSDK3/atcore++.h
We're releasing some new sCMOS cameras soon.  Updating Micromanager AndorSDK3 to support new features on these cameras.
Changes:
Tidying up factory.
Implementing new AuxOut features.
Allowing defaults to be loaded from the SDK.
Loading ReadOnly status from the SDK.
=> Adding support for new larger cameras.

DeviceAdapters/DemoCamera/DemoCamera.h
make getOffset actually return the last offset provided by setOffset
=> Add offset management to DemoAutoFocus class

DeviceAdapters/DemoCamera/DemoCamera.cpp, DeviceAdapters/DemoCamera/DemoCamera.h
- Move member initializers to member definitions
- Remove some unused variables and unnecessary constructors/destructors
=> DemoCamera: Fix compiler warnings

DeviceAdapters/ArduinoCounter/ArduinoCounter.cpp, DeviceAdapters/ArduinoCounter/ArduinoCounter/ArduinoCounter.ino
Fixes bug in sequences when logic is inverted.
=> Arduino counter bug fix, version to 3

DeviceAdapters/IlluminateLEDArray/LEDArray.cpp, DeviceAdapters/IlluminateLEDArray/LEDArray.h
This update includes a number of accumulated changes over the past couple of years which have paired with changes to the [Illuminate LED Array Firmware](https://github.com/sci-microscopy/illuminate). High-level list of changes to this driver include:
- Removal of unused virtual shutter interface
- Usage of error messages that provide context
- Enforcement of a minimum device firmware
- Refactors of various variable names
- Significant simplification of structure (lots of removals)
This is a large PR but has been incrementally tested as firmware changes have progressed. It does not produce warnings within the build to my knowledge.
=> Bump to LED Array API Version 2.0
